# Everforest — (c) sainnhe, MIT; ported, no endorsement implied
name = everforest-dark
appearance = dark

foreground = #d3c6aa
background = #2d353b
clear = #2d353b

cursor = #d3c6aa
selection = #475258
search = #4e4322
border = #484c4d
inactive = #78766d

color0 = #475258
color1 = #e67e80
color2 = #a7c080
color3 = #dbbc7f
color4 = #7fbbb3
color5 = #d699b6
color6 = #83c092
color7 = #d3c6aa
color8 = #56635f
color9 = #e67e80
color10 = #a7c080
color11 = #dbbc7f
color12 = #7fbbb3
color13 = #d699b6
color14 = #83c092
color15 = #d3c6aa
