# Gruvbox light — (c) morhetz, MIT; ported, no endorsement implied
name = gruvbox-light
appearance = light

foreground = #3c3836
background = #fbf1c7
clear = #fbf1c7

cursor = #3c3836
selection = #ebdbb2
search = #f2e5a0
border = #dcd3b0
inactive = #a59e86

color0 = #fbf1c7
color1 = #9d0006
color2 = #79740e
color3 = #b57614
color4 = #076678
color5 = #8f3f71
color6 = #427b58
color7 = #3c3836
color8 = #928374
color9 = #9d0006
color10 = #79740e
color11 = #b57614
color12 = #076678
color13 = #8f3f71
color14 = #427b58
color15 = #7c6f64
