# Iceberg — (c) cocopon, MIT; ported, no endorsement implied
name = iceberg-dark
appearance = dark

foreground = #c6c8d1
background = #161821
clear = #161821

cursor = #84a0c6
selection = #272c42
search = #4a4322
border = #32343d
inactive = #656770

color0 = #1e2132
color1 = #e27878
color2 = #b4be82
color3 = #e2a478
color4 = #84a0c6
color5 = #a093c7
color6 = #89b8c2
color7 = #c6c8d1
color8 = #6b7089
color9 = #e98989
color10 = #c0ca8e
color11 = #e9b189
color12 = #91acd1
color13 = #ada0d3
color14 = #95c4ce
color15 = #d2d4de
