# One Light — Atom (c) GitHub, MIT; ported, no endorsement implied
name = one-light
appearance = light

foreground = #383a42
background = #fafafa
clear = #fafafa

cursor = #4078f2
selection = #dfdfdf
search = #f0e6a8
border = #dbdbdd
inactive = #a3a4a7

color0 = #383a42
color1 = #e45649
color2 = #50a14f
color3 = #986801
color4 = #4078f2
color5 = #a626a4
color6 = #0184bc
color7 = #a0a1a7
color8 = #696c77
color9 = #e45649
color10 = #50a14f
color11 = #c18401
color12 = #4078f2
color13 = #a626a4
color14 = #0184bc
color15 = #383a42
