# Rose Pine Dawn — (c) Rose Pine, MIT; ported, no endorsement implied
name = rose-pine-dawn
appearance = light

foreground = #575279
background = #faf4ed
clear = #faf4ed

cursor = #575279
selection = #dfdad9
search = #f0e2b8
border = #e0dada
inactive = #b1abb9

color0 = #f2e9e1
color1 = #b4637a
color2 = #56949f
color3 = #ea9d34
color4 = #286983
color5 = #907aa9
color6 = #d7827e
color7 = #575279
color8 = #9893a5
color9 = #b4637a
color10 = #56949f
color11 = #ea9d34
color12 = #286983
color13 = #907aa9
color14 = #d7827e
color15 = #575279
