// SPDX-License-Identifier: GPL-3.0-only
//! Structural and coverage checks for the public-safe glyph fixture corpus
//! (`tests/fixtures/glyphs.txt`, generated by `scripts/glyph-fixture.py`).
//!
//! These tests do three jobs:
//! 1. **Public safety** — the corpus ships in a public repo and must contain no
//!    real shell history, local paths, hostnames, emails, or IP addresses. It
//!    must be fully synthetic Unicode plus short labels.
//! 2. **Coverage claims** — every codepoint in a range the corpus advertises as
//!    "rendered geometrically" must satisfy [`odytty::boxdraw::covers`], and
//!    every documented hole must not. This ties the eyeball fixture to the
//!    implementation: a regression (a range silently losing geometric coverage,
//!    or a hole being silently closed without updating the label) is caught.
//! 3. **Structure** — all expected sections are present, so a truncated or stale
//!    regeneration is detected.

use odytty::boxdraw;

/// The committed corpus, embedded at compile time.
const FIXTURE: &str = include_str!("fixtures/glyphs.txt");

/// Section headers the corpus must contain (order-independent).
const EXPECTED_SECTIONS: &[&str] = &[
    "Box drawing",
    "Block elements",
    "Braille patterns",
    "sextants",
    "octants",
    "triangular blocks",
    "eighth strips",
    "DEFERRED — known holes",
    "Powerline symbols",
    "Nerd Font PUA samples",
    "CJK wide text",
    "Combining marks",
    "Emoji",
];

/// Codepoint ranges the corpus advertises as geometrically rendered. Every
/// codepoint must satisfy [`boxdraw::covers`].
const COVERED_RANGES: &[(u32, u32)] = &[
    (0x1FB00, 0x1FB3B), // sextants
    (0x1CD00, 0x1CDE5), // octants
    (0x1FB68, 0x1FB6F), // triangular blocks
    (0x1FB70, 0x1FB7B), // vertical/horizontal eighth strips
    (0x1FB7C, 0x1FB81), // L-combo one-eighth blocks + horizontal block-1358
    (0x1FB82, 0x1FB8B), // upper/right eighth ladders
    (0x1FB8C, 0x1FB8F), // half-shades
    (0x1FBF0, 0x1FBF9), // segmented digits 0-9
];

/// Documented holes. None of these may be geometrically covered yet; the corpus
/// deliberately surfaces them so the gap stays visible.
const HOLE_RANGES: &[(u32, u32)] = &[
    (0x1FB3C, 0x1FB67), // diagonal-edged blocks (need an AA polygon filler)
    (0x1FBBD, 0x1FBBF), // negative diagonals (need an AA polygon filler)
];

#[test]
fn fixture_is_present_and_nonempty() {
    assert!(!FIXTURE.trim().is_empty(), "glyph fixture is empty");
    // Sanity: it carries thousands of glyphs, so it should be at least a few KB.
    assert!(
        FIXTURE.len() > 4_000,
        "glyph fixture looks truncated: {} bytes",
        FIXTURE.len()
    );
}

#[test]
fn fixture_is_valid_and_has_all_sections() {
    for marker in EXPECTED_SECTIONS {
        assert!(
            FIXTURE.contains(marker),
            "glyph fixture missing section marker: {marker:?}"
        );
    }
    assert!(
        FIXTURE.contains("End of corpus."),
        "fixture is missing its trailer"
    );
    // Cheap guard against a hand-edited, stale fixture: the banner must name the
    // generator and the committed path.
    assert!(
        FIXTURE.contains("scripts/glyph-fixture.py")
            && FIXTURE.contains("tests/fixtures/glyphs.txt"),
        "fixture banner no longer references its generator/path"
    );
}

#[test]
fn fixture_contains_no_private_or_local_data() {
    // The corpus is fully synthetic. Reject any line that smells like a local
    // filesystem path, a username/host pair, an email address, or an IPv4
    // address. These exact substrings/patterns must never appear here.
    for (n, line) in FIXTURE.lines().enumerate() {
        let lower = line.to_ascii_lowercase();

        // Local filesystem paths.
        assert!(
            !lower.contains("/home/")
                && !lower.contains("/users/")
                && !lower.contains("c:\\")
                && !lower.contains("/var/")
                && !lower.contains("/etc/"),
            "local path leaked into corpus at line {}: {line}",
            n + 1
        );

        // Username / host pairs from the operator environment.
        assert!(
            !lower.contains("joel@") && !lower.contains("@odyssey"),
            "username/host leaked into corpus at line {}: {line}",
            n + 1
        );

        // No email addresses: the corpus uses no '@' at all. Banning it outright
        // is the clearest guarantee and matches the current synthetic content.
        assert!(
            !line.contains('@'),
            "unexpected '@' (possible email) in corpus at line {}: {line}",
            n + 1
        );

        // No IPv4 addresses.
        assert!(
            !looks_like_ipv4(line),
            "IPv4-like text leaked into corpus at line {}: {line}",
            n + 1
        );
    }
}

#[test]
fn advertised_geometric_ranges_are_actually_covered() {
    for &(lo, hi) in COVERED_RANGES {
        for cp in lo..=hi {
            let ch = char::from_u32(cp).expect("valid codepoint");
            assert!(
                boxdraw::covers(ch),
                "corpus advertises U+{cp:04X} as geometrically rendered, but \
                 boxdraw::covers is false"
            );
            // And it must actually produce coverage bytes at a real cell size.
            assert!(
                boxdraw::coverage(ch, 9, 18).is_some(),
                "U+{cp:04X} is covered but produced no coverage bitmap"
            );
        }
    }
}

#[test]
fn documented_holes_remain_uncovered() {
    for &(lo, hi) in HOLE_RANGES {
        for cp in lo..=hi {
            let ch = char::from_u32(cp).expect("valid codepoint");
            assert!(
                !boxdraw::covers(ch),
                "U+{cp:04X} is now geometrically covered; if intended, move it out \
                 of the DEFERRED section in the fixture and out of HOLE_RANGES"
            );
        }
    }
}

/// True if `line` contains an IPv4-shaped run `octet.octet.octet.octet` (each
/// octet 1–3 digits, ≤255, single dots between them). Rejecting doubled dots
/// (`..`) keeps this from matching codepoint-range notation like `U+E0B0..U+E0B3`.
/// No full regex needed for this synthetic-corpus guard.
fn looks_like_ipv4(line: &str) -> bool {
    let b = line.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i < n {
        // A candidate octet start must not be preceded by a digit or dot.
        if b[i].is_ascii_digit() && (i == 0 || (!b[i - 1].is_ascii_digit() && b[i - 1] != b'.')) {
            if let Some(end) = match_ipv4(b, i) {
                // The match must end at a boundary so it isn't the prefix of a
                // longer run of digits/dots (e.g. a codepoint literal).
                if end == n || (!b[end].is_ascii_digit() && b[end] != b'.') {
                    return true;
                }
                i = end;
                continue;
            }
        }
        i += 1;
    }
    false
}

/// Try to match four dot-separated octets starting at `i`. Returns the index
/// just past the match on success.
fn match_ipv4(b: &[u8], mut i: usize) -> Option<usize> {
    for octet in 0..4 {
        let start = i;
        while i < b.len() && b[i].is_ascii_digit() {
            i += 1;
        }
        let len = i - start;
        if !(1..=3).contains(&len) {
            return None;
        }
        let val: u32 = b[start..i]
            .iter()
            .fold(0u32, |acc, &c| acc * 10 + u32::from(c - b'0'));
        if val > 255 {
            return None;
        }
        if octet < 3 {
            // A single dot immediately followed by a digit (no doubled `..`).
            if i >= b.len() || b[i] != b'.' {
                return None;
            }
            i += 1;
            if i >= b.len() || !b[i].is_ascii_digit() {
                return None;
            }
        }
    }
    Some(i)
}
