// SPDX-License-Identifier: GPL-3.0-only
//! Bidi_Paired_Bracket data, generated by
//! `scripts/unicode-bidi-data.py` from
//! BidiBrackets-17.0.0.txt (SHA-256
//! dadbaf38a0d0246e5b805bf8725cb81b7c621f93d030595635f5ba2c2f179428) and
//! UnicodeData.txt (SHA-256
//! 2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c).
//! The data is Unicode Character Database content, Copyright Unicode, Inc.,
//! under the Unicode License v3 (tests/fixtures/unicode-bidi/LICENSE-UNICODE.txt).
//! Do not edit by hand.

/// 128 brackets sorted by code point: the bracket, the opening
/// bracket of its pair after canonical singleton decomposition, and
/// whether the bracket itself opens.
#[rustfmt::skip]
pub(super) const BIDI_BRACKETS: &[(char, char, bool)] = &[
    ('\u{0028}', '\u{0028}', true), ('\u{0029}', '\u{0028}', false), ('\u{005B}', '\u{005B}', true),
    ('\u{005D}', '\u{005B}', false), ('\u{007B}', '\u{007B}', true),
    ('\u{007D}', '\u{007B}', false), ('\u{0F3A}', '\u{0F3A}', true),
    ('\u{0F3B}', '\u{0F3A}', false), ('\u{0F3C}', '\u{0F3C}', true),
    ('\u{0F3D}', '\u{0F3C}', false), ('\u{169B}', '\u{169B}', true),
    ('\u{169C}', '\u{169B}', false), ('\u{2045}', '\u{2045}', true),
    ('\u{2046}', '\u{2045}', false), ('\u{207D}', '\u{207D}', true),
    ('\u{207E}', '\u{207D}', false), ('\u{208D}', '\u{208D}', true),
    ('\u{208E}', '\u{208D}', false), ('\u{2308}', '\u{2308}', true),
    ('\u{2309}', '\u{2308}', false), ('\u{230A}', '\u{230A}', true),
    ('\u{230B}', '\u{230A}', false), ('\u{2329}', '\u{3008}', true),
    ('\u{232A}', '\u{3008}', false), ('\u{2768}', '\u{2768}', true),
    ('\u{2769}', '\u{2768}', false), ('\u{276A}', '\u{276A}', true),
    ('\u{276B}', '\u{276A}', false), ('\u{276C}', '\u{276C}', true),
    ('\u{276D}', '\u{276C}', false), ('\u{276E}', '\u{276E}', true),
    ('\u{276F}', '\u{276E}', false), ('\u{2770}', '\u{2770}', true),
    ('\u{2771}', '\u{2770}', false), ('\u{2772}', '\u{2772}', true),
    ('\u{2773}', '\u{2772}', false), ('\u{2774}', '\u{2774}', true),
    ('\u{2775}', '\u{2774}', false), ('\u{27C5}', '\u{27C5}', true),
    ('\u{27C6}', '\u{27C5}', false), ('\u{27E6}', '\u{27E6}', true),
    ('\u{27E7}', '\u{27E6}', false), ('\u{27E8}', '\u{27E8}', true),
    ('\u{27E9}', '\u{27E8}', false), ('\u{27EA}', '\u{27EA}', true),
    ('\u{27EB}', '\u{27EA}', false), ('\u{27EC}', '\u{27EC}', true),
    ('\u{27ED}', '\u{27EC}', false), ('\u{27EE}', '\u{27EE}', true),
    ('\u{27EF}', '\u{27EE}', false), ('\u{2983}', '\u{2983}', true),
    ('\u{2984}', '\u{2983}', false), ('\u{2985}', '\u{2985}', true),
    ('\u{2986}', '\u{2985}', false), ('\u{2987}', '\u{2987}', true),
    ('\u{2988}', '\u{2987}', false), ('\u{2989}', '\u{2989}', true),
    ('\u{298A}', '\u{2989}', false), ('\u{298B}', '\u{298B}', true),
    ('\u{298C}', '\u{298B}', false), ('\u{298D}', '\u{298D}', true),
    ('\u{298E}', '\u{298F}', false), ('\u{298F}', '\u{298F}', true),
    ('\u{2990}', '\u{298D}', false), ('\u{2991}', '\u{2991}', true),
    ('\u{2992}', '\u{2991}', false), ('\u{2993}', '\u{2993}', true),
    ('\u{2994}', '\u{2993}', false), ('\u{2995}', '\u{2995}', true),
    ('\u{2996}', '\u{2995}', false), ('\u{2997}', '\u{2997}', true),
    ('\u{2998}', '\u{2997}', false), ('\u{29D8}', '\u{29D8}', true),
    ('\u{29D9}', '\u{29D8}', false), ('\u{29DA}', '\u{29DA}', true),
    ('\u{29DB}', '\u{29DA}', false), ('\u{29FC}', '\u{29FC}', true),
    ('\u{29FD}', '\u{29FC}', false), ('\u{2E22}', '\u{2E22}', true),
    ('\u{2E23}', '\u{2E22}', false), ('\u{2E24}', '\u{2E24}', true),
    ('\u{2E25}', '\u{2E24}', false), ('\u{2E26}', '\u{2E26}', true),
    ('\u{2E27}', '\u{2E26}', false), ('\u{2E28}', '\u{2E28}', true),
    ('\u{2E29}', '\u{2E28}', false), ('\u{2E55}', '\u{2E55}', true),
    ('\u{2E56}', '\u{2E55}', false), ('\u{2E57}', '\u{2E57}', true),
    ('\u{2E58}', '\u{2E57}', false), ('\u{2E59}', '\u{2E59}', true),
    ('\u{2E5A}', '\u{2E59}', false), ('\u{2E5B}', '\u{2E5B}', true),
    ('\u{2E5C}', '\u{2E5B}', false), ('\u{3008}', '\u{3008}', true),
    ('\u{3009}', '\u{3008}', false), ('\u{300A}', '\u{300A}', true),
    ('\u{300B}', '\u{300A}', false), ('\u{300C}', '\u{300C}', true),
    ('\u{300D}', '\u{300C}', false), ('\u{300E}', '\u{300E}', true),
    ('\u{300F}', '\u{300E}', false), ('\u{3010}', '\u{3010}', true),
    ('\u{3011}', '\u{3010}', false), ('\u{3014}', '\u{3014}', true),
    ('\u{3015}', '\u{3014}', false), ('\u{3016}', '\u{3016}', true),
    ('\u{3017}', '\u{3016}', false), ('\u{3018}', '\u{3018}', true),
    ('\u{3019}', '\u{3018}', false), ('\u{301A}', '\u{301A}', true),
    ('\u{301B}', '\u{301A}', false), ('\u{FE59}', '\u{FE59}', true),
    ('\u{FE5A}', '\u{FE59}', false), ('\u{FE5B}', '\u{FE5B}', true),
    ('\u{FE5C}', '\u{FE5B}', false), ('\u{FE5D}', '\u{FE5D}', true),
    ('\u{FE5E}', '\u{FE5D}', false), ('\u{FF08}', '\u{FF08}', true),
    ('\u{FF09}', '\u{FF08}', false), ('\u{FF3B}', '\u{FF3B}', true),
    ('\u{FF3D}', '\u{FF3B}', false), ('\u{FF5B}', '\u{FF5B}', true),
    ('\u{FF5D}', '\u{FF5B}', false), ('\u{FF5F}', '\u{FF5F}', true),
    ('\u{FF60}', '\u{FF5F}', false), ('\u{FF62}', '\u{FF62}', true),
    ('\u{FF63}', '\u{FF62}', false),
];
