// SPDX-License-Identifier: GPL-3.0-only
//! Tail settings rows: Input (continued), Connections, Sessions, Clipboard, Accessibility, Development.

use super::super::*;
use super::{NumericSpec, SettingInfo, SettingKind};

pub(super) fn tail_setting_rows(settings: &Settings) -> Vec<SettingInfo> {
    vec![
        SettingInfo {
            group: "Input",
            key: "interactive_paths_barewords",
            env: INTERACTIVE_PATHS_BAREWORDS_ENV,
            name: "Bare filename paths",
            value: bool_display(settings.interactive_paths_barewords).to_owned(),
            description: "When interactive file paths are on, also consider basename-like tokens with extensions (for example carpet1.jpg) as path candidates. On by default behind the global interactive_paths gate; candidates still resolve through the filesystem check against the pane cwd, so non-existent words stay inert.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Input",
            key: "interactive_paths_click_hint",
            env: INTERACTIVE_PATHS_CLICK_HINT_ENV,
            name: "Click-to-open hint",
            value: bool_display(settings.interactive_paths_click_hint).to_owned(),
            description: "When interactive file paths are on, show a transient bottom-left \"Ctrl+click to open\" hint after two plain mis-clicks on a resolved path land within a short window. On by default behind the global interactive_paths gate. Off silences only the hint; the hand cursor, the Ctrl+hover underline, and Ctrl+click open all still work.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Input",
            key: "interactive_paths_image_inline",
            env: INTERACTIVE_PATHS_IMAGE_INLINE_ENV,
            name: "Inline image paths",
            value: bool_display(settings.interactive_paths_image_inline).to_owned(),
            description: "When interactive file paths are on, Ctrl+clicking a resolved image path opens the in-OdyTTY viewer by default. On by default behind the global interactive_paths gate. Off restores the external opener for images; the right-click Open in OdyTTY action remains available.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Input",
            key: "interactive_paths_editor",
            env: INTERACTIVE_PATHS_EDITOR_ENV,
            name: "Interactive path editor",
            value: if settings.interactive_paths_editor.is_empty() {
                "default".to_owned()
            } else {
                settings.interactive_paths_editor.clone()
            },
            description: "Editor used to open a path with a line/column suffix (path:line:col). Empty (default) detects the editor from $EDITOR/$VISUAL. Set a known editor name (vim, nvim, code, emacs, helix, sublime, nano, micro) or an argv template with {file}, {line}, {col} placeholders. Always passed as an argv vector, never run through a shell.",
            kind: SettingKind::String,
            range: None,
            options: &[],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "ssh_config_hosts",
            env: SSH_CONFIG_HOSTS_ENV,
            name: "Import OpenSSH host names",
            value: bool_display(settings.ssh_config_hosts).to_owned(),
            description: "Opt-in source for the connection manager. Off by default, so OdyTTY never reads OpenSSH config. When on, OdyTTY reads the caller-resolved ~/.ssh/config path read-only and name-only through a bounded parser; key directives and credentials are not surfaced.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "remote_integration",
            env: REMOTE_INTEGRATION_ENV,
            name: "Remote shell integration",
            value: bool_display(settings.remote_integration).to_owned(),
            description: "Inject OdyTTY's OSC 133 shell integration on SSH tabs so a remote bash session gains the same prompt and input boundaries as a local one. Nothing is persisted on the remote; any failure or a non-bash remote shell degrades to a plain ssh session. On by default. A per-host 'Integration off' in hosts.conf opts a single host out; off globally makes every SSH tab's launch byte-identical to a plain ssh.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "remote_reuse",
            env: REMOTE_REUSE_ENV,
            name: "Reuse SSH connections",
            value: bool_display(settings.remote_reuse).to_owned(),
            description: "Multiplex integrated SSH tabs over a shared connection with ControlMaster/ControlPersist and an OdyTTY-owned control socket, so a second tab to the same effective SSH endpoint connects with no new handshake. On by default; if the shared master is gone the tab degrades to a normal fresh connect. A per-host 'Reuse off' in hosts.conf opts a single host out. No effect on a Windows client, where OpenSSH has no connection multiplexing.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "remote_tmux",
            env: REMOTE_TMUX_ENV,
            name: "Persist SSH sessions with tmux",
            value: bool_display(settings.remote_tmux).to_owned(),
            description: "Wrap an integrated SSH tab's remote shell in a persistent tmux session ('tmux new-session -A -s odytty'), so a dropped-and-reconnected link reattaches the same remote session with its running programs and scrollback intact. Off by default; the remote shell degrades to plain bash when the remote has no tmux, so enabling it never breaks a session. A per-host 'Tmux on'/'Tmux off' in hosts.conf overrides for a single host. Only takes effect with remote integration on.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "remote_persist",
            env: REMOTE_PERSIST_ENV,
            name: "Keep SSH connection warm",
            value: settings.remote_persist.as_str().to_owned(),
            description: "How long a reused SSH master connection stays authenticated after the last tab to a host closes, so a daily-driver host is authenticated roughly once per boot rather than once per tab. Default 10m keeps the historical 10-minute window (behavior unchanged); off tears the master down with its last connection. A per-host 'Persist' line in hosts.conf overrides this and accepts any ssh ControlPersist value. Only takes effect with connection reuse on; no effect on a Windows client, where OpenSSH has no connection multiplexing.",
            kind: SettingKind::Enum,
            range: None,
            options: &["off", "10m", "30m", "1h", "2h"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Connections",
            key: "remote_image_paste",
            env: REMOTE_IMAGE_PASTE_ENV,
            name: "Paste clipboard images to remote",
            value: settings.remote_image_paste.as_str().to_owned(),
            description: "Offer to upload a clipboard image pasted into a remote integrated SSH tab. 'ask' (default) prompts before every upload, showing the encoded size and the target host, so image bytes never leave the machine on a keystroke without confirmation; 'off' disables it, so an image paste there does nothing. Only engages on a remote integrated tab; a local or plain-ssh tab's paste is unaffected. Uploads land 0600 in the remote /tmp under an unguessable name and are cleaned up best-effort on tab close.",
            kind: SettingKind::Enum,
            range: None,
            options: &["ask", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "session_replay",
            env: SESSION_REPLAY_ENV,
            name: "Record output for replay",
            value: bool_display(settings.session_replay).to_owned(),
            description: "Opt-in per-session output recording for the scrubbable replay overlay. Off by default, so the PTY pump records nothing and the plain path is byte-identical. When on, each session keeps a bounded in-memory ring of recent screen frames the replay overlay can scrub. Recording is local-only: frames never leave memory (no disk, no network).",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "navigator_preview",
            env: NAVIGATOR_PREVIEW_ENV,
            name: "Session navigator preview",
            value: bool_display(settings.navigator_preview).to_owned(),
            description: "Show up to eight frozen, redacted lines from a selected live pane in Session Navigator. Off by default. Detached sessions never expose a preview; opening or viewing a preview never wakes, attaches, or writes to a session.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "restore_workspaces",
            env: RESTORE_WORKSPACES_ENV,
            name: "Restore workspaces at launch",
            value: bool_display(settings.restore_workspaces).to_owned(),
            description: "When on, launching odytty with no arguments reopens the previous workspace/tab/pane layout \u{2014} workspace names, tab titles and order, and each pane's split tree at its captured directory, each with a fresh shell. Never restores terminal output, scrollback, or commands (shape only). Off by default; any command-line argument starts fresh for that launch. The layout autosave runs regardless, so a snapshot is ready the moment this is turned on.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "profile_auto_switch",
            env: PROFILE_AUTO_SWITCH_ENV,
            name: "Auto-switch named profiles",
            value: bool_display(settings.profile_auto_switch).to_owned(),
            description: "When on, the focused local pane may adopt a different named profile when its working directory or trusted remote host matches switch rules declared in local profile files. A short HUD notice names the profile and match reason. Off by default; terminal output cannot select, rewrite, or create profiles.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "default_launch_profile",
            env: DEFAULT_LAUNCH_PROFILE_ENV,
            name: "Default launch profile",
            value: settings
                .default_launch_profile
                .clone()
                .unwrap_or_else(|| "(System Default)".to_owned()),
            description: "Named profile used by plain New Tab and New Workspace when the active workspace has no profile override. Missing or invalid names fall back to the built-in System Default with a one-line notice. Set from Profile Manager; never applied on the ordinary startup path unless a spawn explicitly requests it.",
            kind: SettingKind::String,
            range: None,
            options: &[],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Sessions",
            key: "shell_exit_closes",
            env: SHELL_EXIT_CLOSES_ENV,
            name: "Typing exit closes",
            value: settings.shell_exit_closes.as_str().to_owned(),
            description: "What typing exit (or Ctrl-D on a live shell) does when it would close a whole workspace. Workspace (default) closes just that workspace, exactly as before; closing the last workspace still quits. Application quits OdyTTY instead whenever a shell exit would close a workspace, even if other workspaces are open \u{2014} it pairs with Restore workspaces so the same set reopens next launch. Either way the rail close button and the close-tab / close-workspace / close-pane keybinds still close a single surface, and exiting a shell that has sibling tabs or panes still closes only that tab or pane.",
            kind: SettingKind::Enum,
            range: None,
            options: &["workspace", "app"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Clipboard",
            key: "osc52_write",
            env: OSC52_WRITE_ENV,
            name: "Terminal clipboard writes (OSC 52)",
            value: settings.osc52_write.as_str().to_owned(),
            description: "Controls clipboard writes requested by terminal output. Ask (default) requires ephemeral per-session approval before a program replaces the clipboard, On preserves copy workflows by applying focused writes immediately, and Off discards writes. Every mode permanently discards requests from background sessions or while the OS window is unfocused.",
            kind: SettingKind::Enum,
            range: None,
            options: &["off", "ask", "on"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Clipboard",
            key: "osc52_read",
            env: OSC52_READ_ENV,
            name: "Allow clipboard read (OSC 52)",
            value: bool_display(settings.osc52_read).to_owned(),
            description: "Allows terminal applications to query local clipboard contents through OSC 52 replies. Off by default for safety; clipboard writes are separate.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Clipboard",
            key: "copy_on_select",
            env: COPY_ON_SELECT_ENV,
            name: "Copy selection to clipboard",
            value: bool_display(settings.copy_on_select).to_owned(),
            description: "When on, finishing a mouse selection also copies it to the clipboard. Off by default - the primary selection and middle-click paste work either way.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Clipboard",
            key: "smart_ctrl_c",
            env: SMART_CTRL_C_ENV,
            name: "Smart Ctrl+C (copy or interrupt)",
            value: settings.smart_ctrl_c.as_str().to_owned(),
            description: "What plain Ctrl+C does. Copy-or-interrupt (default): when text is selected, Ctrl+C copies it and clears the selection; with nothing selected, Ctrl+C still sends the interrupt. Off always sends the interrupt signal (^C), as a terminal normally does. To still interrupt while text is selected, press Esc first (or Ctrl+C twice). Ctrl+Shift+V pastes, and Ctrl+Shift+C always copies, regardless of this setting.",
            kind: SettingKind::Enum,
            range: None,
            options: &["off", "copy-or-interrupt"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Accessibility",
            key: "reduced_motion",
            env: REDUCED_MOTION_ENV,
            name: "Reduce motion",
            value: bool_display(settings.reduced_motion).to_owned(),
            description: "When on, cursor slide, trail, glow, blink fade, and new-output fade use static or instant behavior. Their individual settings remain saved unchanged. This explicit setting behaves the same on Windows, macOS, and Linux; OS reduced-motion preference discovery is not yet available.",
            kind: SettingKind::Bool,
            range: None,
            options: &["on", "off"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Accessibility",
            key: "cvd_mode",
            env: CVD_MODE_ENV,
            name: "Color-blind adaptation",
            value: settings.cvd_mode.as_str().to_owned(),
            description: "Adapts the palette so colors that a color-vision deficiency confuses become distinguishable, while staying readable. Off by default. Protan and deutan target red-green confusion, tritan targets blue-yellow.",
            kind: SettingKind::Enum,
            range: None,
            options: &["off", "protan", "deutan", "tritan"],
            reloadable: true,
            numeric: None,
        },
        SettingInfo {
            group: "Accessibility",
            key: "cvd_strength",
            env: CVD_STRENGTH_ENV,
            name: "Color-blind adaptation strength",
            value: format_float(settings.cvd_strength),
            description: "How strongly the palette is shifted toward separability for the selected color-blind mode. 1.0 is the full correction, 0.0 is no change. Has no effect while the mode is off.",
            kind: SettingKind::Number,
            range: None,
            options: &[],
            reloadable: true,
            numeric: Some(NumericSpec {
                min: MIN_CVD_STRENGTH,
                max: MAX_CVD_STRENGTH,
                step: 0.1,
                unit: "",
            }),
        },
        SettingInfo {
            group: "Development",
            key: "native_autoclose_ms",
            env: NATIVE_AUTOCLOSE_ENV,
            name: "Native autoclose",
            value: settings
                .native_autoclose
                .map(|duration| format!("{} ms", duration.as_millis()))
                .unwrap_or_else(|| "unset".to_owned()),
            description: "Smoke-test helper that closes the native window after a startup delay. It is startup-only, not live-reloadable.",
            kind: SettingKind::Number,
            range: Some("positive milliseconds".to_owned()),
            options: &[],
            reloadable: false,
            numeric: None,
        },
    ]
}
