// SPDX-License-Identifier: GPL-3.0-only
//! Authoritative settings-row metadata in stable display order.

use super::super::*;
use super::order::{numeric_range_label, setting_group_rank};

/// Broad setting type hint for the read-only UX2-a panel and later editors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingKind {
    Bool,
    Enum,
    Number,
    String,
    Path,
    List,
}

/// Structured numeric bounds for a [`SettingKind::Number`] row (UX4-P2): the
/// authoritative `(min, max, step)` shared by the settings stepper, keyboard
/// step, and any fraction-based test helpers, plus an optional display `unit`
/// (e.g. `"px"`). `min`/`max` mirror the same constants the parser clamps to,
/// so the UI controls, keyboard step, derived range label, and live-apply clamp
/// are one source of truth and cannot drift. `unit` exists only so the derived
/// range label keeps its suffix losslessly; the `{min, max, step}` core is
/// exactly the modeled spec.
///
/// `f32` fields mean this (and therefore [`SettingInfo`]) cannot derive `Eq`;
/// `PartialEq` is sufficient for every consumer.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct NumericSpec {
    pub min: f32,
    pub max: f32,
    pub step: f32,
    pub unit: &'static str,
}

impl NumericSpec {
    /// Position of `value` along the track as a `0.0..=1.0` fraction (clamped),
    /// used to place the slider thumb. A degenerate `min == max` maps to `0.0`.
    pub fn fraction_of(&self, value: f32) -> f32 {
        let span = self.max - self.min;
        if span.abs() < f32::EPSILON {
            return 0.0;
        }
        ((value - self.min) / span).clamp(0.0, 1.0)
    }

    /// Value at a `0.0..=1.0` track fraction (clamped), snapped to `step` and
    /// clamped back into `[min, max]`. The live-apply parser clamps again, so
    /// this only needs to be approximately in-range.
    pub fn value_at_fraction(&self, fraction: f32) -> f32 {
        let raw = self.min + fraction.clamp(0.0, 1.0) * (self.max - self.min);
        self.snap(raw)
    }

    /// Snap a raw value to the nearest `step` from `min`, clamped to `[min, max]`.
    pub fn snap(&self, value: f32) -> f32 {
        let snapped = if self.step > f32::EPSILON {
            self.min + ((value - self.min) / self.step).round() * self.step
        } else {
            value
        };
        snapped.clamp(self.min, self.max)
    }

    /// Stable character budget reserved for the numeric readout: the
    /// wider of the two bound labels plus room for the `" *"` changed marker, so
    /// row geometry does not shift as the live value (or its marker) changes.
    pub fn readout_width(&self) -> usize {
        let lo = format_float(self.min).chars().count();
        let hi = format_float(self.max).chars().count();
        lo.max(hi) + 2
    }
}

/// Static/dynamic metadata for one settings row in stable display order.
#[derive(Debug, Clone, PartialEq)]
pub struct SettingInfo {
    pub group: &'static str,
    pub key: &'static str,
    pub env: &'static str,
    pub name: &'static str,
    pub value: String,
    pub description: &'static str,
    pub kind: SettingKind,
    /// Human-readable allowed-range hint. For [`SettingKind::Number`] rows with
    /// a [`NumericSpec`] this is derived from the spec (UX4-P2, Q4) so it can
    /// never drift from the clamp bounds; other rows carry a literal hint or
    /// `None`.
    pub range: Option<String>,
    /// Structured numeric bounds for slider/step/clamp (UX4-P2). `Some` for
    /// bounded, live-editable [`SettingKind::Number`] rows; `None` otherwise.
    pub numeric: Option<NumericSpec>,
    pub options: &'static [&'static str],
    pub reloadable: bool,
}

impl Settings {
    /// Stable read-only inventory for the in-app settings panel.
    ///
    /// This intentionally mirrors every field on [`Settings`]. UX2-b can attach
    /// editors and persistence to the same rows; UX2-a only displays them.
    pub fn setting_info(&self) -> Vec<SettingInfo> {
        let mut rows = vec![
            SettingInfo {
                group: "Theme",
                key: "theme",
                env: THEME_ENV,
                name: "Theme",
                // When the `system` alias is active the displayed value is the
                // alias token, matching the config writeback; a file-loaded
                // theme shows its original config string, never the `"custom"`
                // placeholder — the shared round-trip helper keeps the panel and
                // the writeback baseline in lockstep (C4).
                value: self.theme_config_value(),
                description: "Full appearance profile: default colors, ANSI palette, semantic role colors, and optional user theme files.",
                kind: SettingKind::Enum,
                range: None,
                options: &[
                    "system",
                    "plain",
                    "odyssey-classic",
                    "odyssey-noir",
                    "user theme name",
                    "theme file path",
                ],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "follow_os_theme",
                env: FOLLOW_OS_THEME_ENV,
                name: "Follow OS dark/light theme",
                value: bool_display(self.follow_os_theme).to_owned(),
                description: "When on, switches between the dark and light themes below based on the desktop's color-scheme preference. The compositor delivers this live on Wayland; on X11 set ODYTTY_APPEARANCE=dark|light to seed it. Off by default — the OS signal is ignored and the theme above drives presentation. A direction whose theme name is unset keeps the authored theme.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "follow_external_palette",
                env: FOLLOW_EXTERNAL_PALETTE_ENV,
                name: "Follow external palette",
                value: bool_display(self.follow_external_palette).to_owned(),
                description: "External palette following: when on, apply a complete palette from an explicit local file through the theme seam and retain the last known-good palette across missing or malformed replacement. Off by default; no discovery, read, parse, or poll happens on the ordinary first-terminal path.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "external_palette_provider",
                env: EXTERNAL_PALETTE_PROVIDER_ENV,
                name: "External palette provider",
                value: self.external_palette_provider.as_str().to_owned(),
                description: "Provider for External palette following. odytty = explicit OdyTTY/Base16 complete file; colors_toml = Omarchy-compatible colors.toml (independent compatibility); colors_json = pywal-compatible colors.json (independent compatibility). No endorsement or upstream integration is implied.",
                kind: SettingKind::Enum,
                range: None,
                options: &["odytty", "colors_toml", "colors_json"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "external_palette_path",
                env: EXTERNAL_PALETTE_PATH_ENV,
                name: "External palette path",
                value: self
                    .external_palette_path
                    .clone()
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "Explicit filesystem path of the palette file to follow. Required when Follow external palette is on. Never set from terminal output.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "external_palette_status",
                env: "",
                name: "External palette status",
                value: if self.follow_external_palette {
                    "pending".to_owned()
                } else {
                    "off".to_owned()
                },
                description: "Live follower state: off, watching, applied, retained (last known-good held after a read error), or error with validation detail. Read-only; updates after apply and poll.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: false,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "os_theme_dark",
                env: OS_THEME_DARK_ENV,
                name: "Dark OS theme",
                value: self
                    .os_theme_dark
                    .clone()
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "Theme applied when Follow OS theme is on and the desktop reports a dark color scheme. Resolved by name against the built-in theme library; unset keeps the authored theme on a dark signal.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "os_theme_light",
                env: OS_THEME_LIGHT_ENV,
                name: "Light OS theme",
                value: self
                    .os_theme_light
                    .clone()
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "Theme applied when Follow OS theme is on and the desktop reports a light color scheme. Resolved by name against the built-in theme library; unset keeps the authored theme on a light signal.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "visual",
                env: VISUAL_ENV,
                name: "Ambient visual effect",
                value: self.visual.as_str().to_owned(),
                description: "Ambient scanline look, produced by the unified CRT post-process: ambient turns on CRT scanlines when no explicit crt setting is present, and an explicit crt setting always wins. Requires a GPU adapter with filterable 16-bit float support; falls back to no effect otherwise. Off keeps the renderer plain and is the fastest, most compatible option.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "ambient"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "font",
                env: FONT_ENV,
                name: "Font file (advanced)",
                // Display the RAW explicit `font` key, never the effective
                // `font_path` (RC4): picking a `font_family` resolves a regular
                // face INTO `font_path`, but the advanced row must stay empty
                // because the user never set an explicit file. An UNSET explicit
                // font carries an EMPTY value, not a human sentence — this `value`
                // is what the path-picker seeds and what the writeback compares;
                // empty is treated as a clear (apply_raw("font", "")), so an
                // untouched font emits no edit. The default hint lives in the
                // description below, not in the value.
                value: self
                    .explicit_font_path
                    .as_ref()
                    .map(|path| path.display().to_string())
                    .unwrap_or_default(),
                description: "Advanced: an explicit path to one font file, used instead of the system font lookup. Leave empty (the default: the probed monospace font, or the Font family setting) unless you want to force a specific file. When set, it takes precedence over Font family and falls back safely if the file is missing or unreadable.",
                kind: SettingKind::Path,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "font_family",
                env: FONT_FAMILY_ENV,
                name: "Font family",
                value: self
                    .font_family
                    .clone()
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "System font family lookup for the regular monospace face. Ignored when an explicit font file is set.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "font_weight",
                env: FONT_WEIGHT_ENV,
                name: "Font weight variant",
                value: if self.font_weight.is_empty() {
                    "regular".to_owned()
                } else {
                    self.font_weight.clone()
                },
                description: "Weight-variant suffix for the base face (e.g. Light, Medium, SemiBold). Empty uses the family's regular face. Bold still renders distinctly. Unknown variants fall back to regular with a warning.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "font_size",
                env: FONT_SIZE_ENV,
                name: "Font size",
                value: format_float(self.font_size_px),
                description: "Native font size in pixels. Rebuilds the glyph atlas, cell metrics, terminal grid, and PTY window size.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_FONT_SIZE_PX,
                    max: MAX_FONT_SIZE_PX,
                    step: 1.0,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "ligatures",
                env: LIGATURES_ENV,
                name: "Programming ligatures",
                value: bool_display(self.ligatures).to_owned(),
                description: "Shapes eligible Latin/operator runs with the font's calt and liga features, and Arabic joining forms in logical cell order when the face covers Arabic. On by default. Grid cells, cursor positions, selection, and copied text stay unchanged; unsupported fonts keep scalar glyphs. Optional ss01/ss02 ride separate settings.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "ss01",
                env: LIGATURE_SS01_ENV,
                name: "Stylistic set ss01",
                value: bool_display(self.ligature_ss01).to_owned(),
                description: "Optional OpenType stylistic set ss01 on Latin/operator shaping runs. Off by default. Only applies while programming ligatures are on; no other ssXX tags are exposed.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "ss02",
                env: LIGATURE_SS02_ENV,
                name: "Stylistic set ss02",
                value: bool_display(self.ligature_ss02).to_owned(),
                description: "Optional OpenType stylistic set ss02 on Latin/operator shaping runs. Off by default. Only applies while programming ligatures are on; no other ssXX tags are exposed.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "kitty_named_transports",
                env: KITTY_NAMED_TRANSPORTS_ENV,
                name: "Kitty named transports",
                value: bool_display(self.kitty_named_transports).to_owned(),
                description: "Allows Kitty graphics file, temporary-file, and POSIX shared-memory transports named by terminal output. Off by default because all PTY output, including plain SSH, can request local host I/O; direct and chunked-inline graphics stay enabled.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "text_gamma",
                env: TEXT_GAMMA_ENV,
                name: "Text gamma",
                value: format_float(self.text_gamma),
                description: "Gamma curve applied to glyph coverage when drawing text. Increasing it makes strokes appear heavier and darker; decreasing it makes them lighter and thinner.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TEXT_GAMMA,
                    max: MAX_TEXT_GAMMA,
                    step: 0.1,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "text_brightness",
                env: TEXT_BRIGHTNESS_ENV,
                name: "Text brightness",
                value: format_float(self.text_brightness),
                description: "Lifts glyph ink toward white in linear light so text stays legible over busy or colored backdrops. 1.0 keeps the exact theme colors; higher values brighten strokes up to 1.5. Applies after the minimum-contrast floor and does not affect color emoji.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TEXT_BRIGHTNESS,
                    max: MAX_TEXT_BRIGHTNESS,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "stem_darken",
                env: STEM_DARKEN_ENV,
                name: "Stem darkening",
                value: format_float(self.stem_darken),
                description: STEM_DARKEN_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_STEM_DARKEN,
                    max: MAX_STEM_DARKEN,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "min_contrast",
                env: MIN_CONTRAST_ENV,
                name: "Minimum contrast",
                value: format_float(self.min_contrast),
                description: MIN_CONTRAST_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_MIN_CONTRAST,
                    max: MAX_MIN_CONTRAST,
                    step: 1.0,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "focus_dim",
                env: FOCUS_DIM_ENV,
                name: "Focus dimming",
                value: format_float(self.focus_dim),
                description: FOCUS_DIM_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_FOCUS_DIM,
                    max: MAX_FOCUS_DIM,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Panes",
                key: "inactive_pane_dim",
                env: INACTIVE_PANE_DIM_ENV,
                name: "Inactive-pane dimming",
                value: format_float(self.inactive_pane_dim),
                description: INACTIVE_PANE_DIM_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_INACTIVE_PANE_DIM,
                    max: MAX_INACTIVE_PANE_DIM,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "render_quality",
                env: RENDER_QUALITY_ENV,
                name: "Renderer profile",
                value: self.render_quality.as_str().to_owned(),
                description: RENDER_QUALITY_DESC,
                kind: SettingKind::Enum,
                range: None,
                options: &["plain", "balanced", "high"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "window_padding",
                env: WINDOW_PADDING_ENV,
                name: "Window padding",
                value: format_float(self.window_padding_px),
                description: WINDOW_PADDING_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_WINDOW_PADDING_PX,
                    max: MAX_WINDOW_PADDING_PX,
                    step: 1.0,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "window_border",
                env: WINDOW_BORDER_ENV,
                name: "Window border",
                value: bool_display(self.window_border).to_owned(),
                description: "When on, a thin border in the theme border color frames the terminal grid. Drawn inside the window padding band so it never covers cell text, scaled to the display DPI, and tracks the content on resize. Off by default. Purely visual.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "window_decorations",
                env: WINDOW_DECORATIONS_ENV,
                name: "Window decorations",
                value: bool_display(self.window_decorations).to_owned(),
                description: "When on, the window keeps its title bar and borders; off requests a borderless surface. On by default. Applies at startup and live. Effect depends on the environment: Wayland compositors remove the title bar reliably; X11 window managers honor it on a best-effort basis.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "window_transparency",
                env: WINDOW_TRANSPARENCY_ENV,
                name: "Window transparency",
                value: bool_display(self.window_transparency).to_owned(),
                description: "When on, the terminal background is drawn at the Window opacity below so the desktop shows through; text, cursor, and every overlay (menus, pickers, settings) stay fully opaque. Selection strength is independent and defaults to fully opaque. On by default — at full Window opacity the render is byte-identical to the opaque path. Requires platform compositing (Wayland and macOS natively; X11 needs a compositor; Windows uses DWM). Where no alpha compositing is offered the toggle has no visible effect.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "window_opacity",
                env: WINDOW_OPACITY_ENV,
                name: "Window opacity",
                value: format_float(self.window_opacity),
                description: "Background opacity as a percent when Window transparency is on: 100 is fully opaque, lower values let more of the desktop through behind the terminal. Only the background scales — text and overlays never fade. Adjust with the stepper or arrow keys.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_WINDOW_OPACITY,
                    max: MAX_WINDOW_OPACITY,
                    step: 5.0,
                    unit: "%",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "selection_opacity",
                env: SELECTION_OPACITY_ENV,
                name: "Selection opacity",
                value: format_float(self.selection_opacity),
                description: SELECTION_OPACITY_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_SELECTION_OPACITY,
                    max: MAX_SELECTION_OPACITY,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "colored_bg_opacity",
                env: COLORED_BG_OPACITY_ENV,
                name: "Colored background strength",
                value: format_float(self.colored_bg_opacity),
                description: "Minimum background strength for cells whose color differs from the theme default, so colored blocks like prompt segments and button chips stay solid as Window opacity drops. 0.9 by default; 1 removes Window-opacity attenuation from those cells, restoring their full configured background opacity, while 0 disables the floor. No effect when Window opacity is 100.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_COLORED_BG_OPACITY,
                    max: MAX_COLORED_BG_OPACITY,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Tabs",
                key: "always_show_tab_bar",
                env: ALWAYS_SHOW_TAB_BAR_ENV,
                name: "Always show tab bar",
                value: bool_display(self.always_show_tab_bar).to_owned(),
                description: "When on, the tab bar stays visible even with a single tab. Off by default, so one unnamed tab shows no bar. A single tab you have renamed always shows the bar regardless, so a named workflow tab is never hidden. Applies live.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_bar_placement",
                env: TAB_BAR_PLACEMENT_ENV,
                name: "Rail side",
                value: self.tab_bar_placement.rail_side_str().to_owned(),
                description: "Which side of the terminal content the workspace rail sits on: left (default) or right. Tabs always render on the top bar. Applies live.",
                kind: SettingKind::Enum,
                range: None,
                options: &["left", "right"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Workspace rail",
                key: "workspace_rail",
                env: WORKSPACE_RAIL_ENV,
                name: "Rail visibility",
                value: self.workspace_rail.as_str().to_owned(),
                description: "When the workspace rail is shown: auto (default, appears once a second workspace exists) or always (pinned even with a single workspace). The side is set by \"Rail side\". Applies live.",
                kind: SettingKind::Enum,
                range: None,
                options: &["auto", "always"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Tabs",
                key: "tab_bar_height",
                env: TAB_BAR_HEIGHT_ENV,
                name: "Tab bar height",
                value: self.tab_bar_height.as_config_string(),
                description: "Top tab bar height: \"auto\" is one text row, or a fixed row count for a taller band with the labels centered vertically. Adjust with the stepper or arrow keys; stepping below the minimum returns to auto. Drag the tab bar's bottom edge to set a manual height; double-click it to return to auto. Top bar only. Applies live.",
                kind: SettingKind::Number,
                range: Some(format!(
                    "auto or {}-{} rows",
                    MIN_TAB_BAR_ROWS as usize, MAX_TAB_BAR_ROWS as usize
                )),
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_BAR_ROWS,
                    max: MAX_TAB_BAR_ROWS,
                    step: 1.0,
                    unit: "rows",
                }),
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_width",
                env: TAB_RAIL_WIDTH_ENV,
                name: "Rail width",
                value: self.tab_rail_width.as_config_string(),
                description: "Vertical workspace rail width: \"auto\" sizes to the longest workspace name (up to the rail max width), or a fixed cell count. Drag the rail's inner edge to set a manual width; double-click it to return to auto. Rail placements only. Applies live.",
                kind: SettingKind::String,
                range: Some(format!(
                    "auto or {}-{} cells",
                    MIN_TAB_RAIL_WIDTH as usize, MAX_TAB_RAIL_WIDTH as usize
                )),
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_max_width",
                env: TAB_RAIL_MAX_WIDTH_ENV,
                name: "Rail max width",
                value: format_float(self.tab_rail_max_width),
                description: "Widest the auto-sized workspace rail grows to fit long workspace names before truncating them with an ellipsis. Only used when the rail width is \"auto\". Rail placements only. Applies live.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_RAIL_MAX_WIDTH,
                    max: MAX_TAB_RAIL_MAX_WIDTH,
                    step: 1.0,
                    unit: "cells",
                }),
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_gap",
                env: TAB_RAIL_GAP_ENV,
                name: "Rail slot gap",
                value: format_float(self.tab_rail_gap),
                description: "Rows of empty space between adjacent workspace rail slots (the top margin before the first slot follows it). Rail placements only. Applies live.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_RAIL_GAP,
                    max: MAX_TAB_RAIL_GAP,
                    step: 1.0,
                    unit: "rows",
                }),
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_slot_rows",
                env: TAB_RAIL_SLOT_ROWS_ENV,
                name: "Rail slot height",
                value: format_float(self.tab_rail_slot_rows),
                description: "Rows each workspace rail slot occupies: 1 for a compact single-row list (labels truncate), 2 for the padded default that can wrap a long workspace name across two rows. Rail placements only. Applies live.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_RAIL_SLOT_ROWS,
                    max: MAX_TAB_RAIL_SLOT_ROWS,
                    step: 1.0,
                    unit: "rows",
                }),
            },
            SettingInfo {
                group: "Panel",
                key: "tab_panel_strength",
                env: TAB_PANEL_STRENGTH_ENV,
                name: "Tab panel strength",
                value: format_float(self.tab_panel_strength),
                description: "Sets the opacity of the panel behind the tab bar and rail directly. 0 turns the panel off for bare labels over the window background; 1 makes the band nearly opaque at any window opacity. The default 0.8 keeps a strong panel with a hint of the window showing through. Both placements. Applies live.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_PANEL_STRENGTH,
                    max: MAX_TAB_PANEL_STRENGTH,
                    step: 0.1,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Panel",
                key: "tab_seam",
                env: TAB_SEAM_ENV,
                name: "Tab panel seam",
                value: bool_display(self.tab_seam).to_owned(),
                description: "When on, a thin hairline separates the tab panel from the terminal content. Off removes the line only; the panel stays. Both placements. Applies live.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_autohide",
                env: TAB_RAIL_AUTOHIDE_ENV,
                name: "Rail auto-hide",
                value: bool_display(self.tab_rail_autohide).to_owned(),
                description: "When on, the vertical workspace rail stays hidden until the pointer reaches the window edge, then reveals as a floating overlay (no content reflow). Rail placements only — no effect when tabs are placed on top; use \"Always show tab bar\" for the top bar. Off by default.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Workspace rail",
                key: "tab_rail_reveal_px",
                env: TAB_RAIL_REVEAL_PX_ENV,
                name: "Rail reveal zone",
                value: format_float(self.tab_rail_reveal_px),
                description: "Width in logical pixels of the window-edge zone that reveals an auto-hidden workspace rail on hover (scaled for HiDPI displays). Rail placements only.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_TAB_RAIL_REVEAL_PX,
                    max: MAX_TAB_RAIL_REVEAL_PX,
                    step: 1.0,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "retro",
                env: RETRO_ENV,
                name: "Retro preset",
                value: bool_display(self.retro).to_owned(),
                description: RETRO_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "crt",
                env: CRT_ENV,
                name: "CRT profile",
                value: bool_display(self.crt).to_owned(),
                description: CRT_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom",
                env: BLOOM_ENV,
                name: "Bloom",
                value: bool_display(self.bloom).to_owned(),
                description: BLOOM_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_threshold",
                env: BLOOM_THRESHOLD_ENV,
                name: "Bloom threshold",
                value: format_float(self.bloom_threshold),
                description: BLOOM_THRESHOLD_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_BLOOM_THRESHOLD,
                    max: MAX_BLOOM_THRESHOLD,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_intensity",
                env: BLOOM_INTENSITY_ENV,
                name: "Bloom intensity",
                value: format_float(self.bloom_intensity),
                description: BLOOM_INTENSITY_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_BLOOM_INTENSITY,
                    max: MAX_BLOOM_INTENSITY,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_radius",
                env: BLOOM_RADIUS_ENV,
                name: "Bloom radius",
                value: format_float(self.bloom_radius),
                description: BLOOM_RADIUS_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_BLOOM_RADIUS,
                    max: MAX_BLOOM_RADIUS,
                    step: 0.5,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_scanline_intensity",
                env: CRT_SCANLINE_INTENSITY_ENV,
                name: "CRT scanlines",
                value: format_float(self.crt_scanline_intensity),
                description: CRT_SCANLINE_INTENSITY_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_CRT_SCANLINE_INTENSITY,
                    max: MAX_CRT_SCANLINE_INTENSITY,
                    step: 0.01,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_scanline_period",
                env: CRT_SCANLINE_PERIOD_ENV,
                name: "CRT scanline spacing",
                value: format_float(self.crt_scanline_period),
                description: CRT_SCANLINE_PERIOD_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_CRT_SCANLINE_PERIOD,
                    max: MAX_CRT_SCANLINE_PERIOD,
                    step: 0.5,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_vignette_strength",
                env: CRT_VIGNETTE_STRENGTH_ENV,
                name: "CRT vignette",
                value: format_float(self.crt_vignette_strength),
                description: CRT_VIGNETTE_STRENGTH_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_CRT_VIGNETTE_STRENGTH,
                    max: MAX_CRT_VIGNETTE_STRENGTH,
                    step: 0.01,
                    unit: "",
                }),
            },
            // CRT curvature is intentionally absent from the settings panel: it
            // is a niche barrel-distortion tweak that stays available through
            // the `crt_curvature` config key / ODYTTY_CRT_CURVATURE env only.
            // The knob is the only source of curvature; the retro preset does
            // not override it.
            SettingInfo {
                group: "Post-process",
                key: "background_treatment",
                env: BACKGROUND_TREATMENT_ENV,
                name: "Background treatment",
                value: self.background_treatment.as_str().to_owned(),
                description: BACKGROUND_TREATMENT_DESC,
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "gradient", "vignette", "image"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "background_image",
                env: BACKGROUND_IMAGE_ENV,
                name: "Background image",
                value: self
                    .background_image
                    .as_ref()
                    .map(|path| {
                        if crate::settings::is_bundled_background(path) {
                            format!("{} (bundled)", crate::settings::BUNDLED_BACKGROUND_TOKEN)
                        } else {
                            path.display().to_string()
                        }
                    })
                    .unwrap_or_else(|| "none".to_owned()),
                description: BACKGROUND_IMAGE_DESC,
                kind: SettingKind::Path,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "cell_bg_opacity",
                env: CELL_BG_OPACITY_ENV,
                name: "Wallpaper visibility",
                value: format_float(1.0 - self.cell_bg_opacity),
                description: CELL_BG_OPACITY_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_CELL_BG_OPACITY,
                    max: MAX_CELL_BG_OPACITY,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "background_blur_radius",
                env: BACKGROUND_BLUR_RADIUS_ENV,
                name: "Background blur radius",
                value: self.background_blur_radius.to_string(),
                description: BACKGROUND_BLUR_RADIUS_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: 0.0,
                    max: MAX_BACKGROUND_BLUR_RADIUS as f32,
                    step: 1.0,
                    unit: "px",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "background_image_scrim",
                env: BACKGROUND_IMAGE_SCRIM_ENV,
                name: "Wallpaper readability",
                value: self
                    .background_image_scrim
                    .map(format_float)
                    .unwrap_or_else(|| "auto".to_owned()),
                description: BACKGROUND_IMAGE_SCRIM_DESC,
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_BACKGROUND_IMAGE_SCRIM,
                    max: MAX_BACKGROUND_IMAGE_SCRIM,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Post-process",
                key: "new_output_fade",
                env: NEW_OUTPUT_FADE_ENV,
                name: "New-output fade-in",
                value: bool_display(self.new_output_fade).to_owned(),
                description: "When on, the text of freshly arrived output rows fades in over a short ramp at the live tail instead of appearing instantly. Only the text ramps, from a visible floor to full strength; backgrounds render as normal from the first frame, so nothing darkens. On by default; only at the live tail — scrollback and resize snap. Purely visual.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Post-process",
                key: "new_output_fade_ms",
                env: NEW_OUTPUT_FADE_MS_ENV,
                name: "New-output fade duration",
                value: format_float(self.new_output_fade_ms),
                description: "How long the new-output fade-in takes, in milliseconds. A longer value makes the ramp easy to see; a shorter one restores the original quick fade. Only acts while New-output fade-in is on. Purely visual.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_NEW_OUTPUT_FADE_MS,
                    max: MAX_NEW_OUTPUT_FADE_MS,
                    step: 25.0,
                    unit: "ms",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "subpixel",
                env: SUBPIXEL_ENV,
                name: "Subpixel antialiasing",
                value: subpixel_display(self.subpixel).to_owned(),
                description: "Optional RGB or BGR subpixel antialiasing for crisper text on most LCD displays. Off by default. Unsupported adapters fall back to grayscale antialiasing.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "rgb", "bgr"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "line_height",
                env: LINE_HEIGHT_ENV,
                name: "Line height",
                value: format_float(self.line_height),
                description: "Vertical leading multiplier per text row. 1.0 is the natural cell height; higher values add breathing room above and below each line.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_LINE_HEIGHT,
                    max: MAX_LINE_HEIGHT,
                    step: 0.05,
                    unit: "x",
                }),
            },
            SettingInfo {
                group: "Rendering",
                key: "synthetic_styles",
                env: SYNTHETIC_STYLES_ENV,
                name: "Synthesize bold & italic",
                value: bool_display(self.synthetic_styles).to_owned(),
                description: "Synthesizes missing bold and italic faces from the regular font when real style faces are unavailable.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "geometric_boxdraw",
                env: GEOMETRIC_BOXDRAW_ENV,
                name: "Geometric box-drawing",
                value: bool_display(self.geometric_boxdraw).to_owned(),
                description: GEOMETRIC_BOXDRAW_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Rendering",
                key: "box_thickness",
                env: BOX_THICKNESS_ENV,
                name: "Box-drawing thickness",
                value: format_float(self.box_thickness),
                description: "Scales the geometric box-drawing line weight. 1.0 keeps the default stroke; lower is thinner, higher is heavier.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_BOX_THICKNESS,
                    max: MAX_BOX_THICKNESS,
                    step: 0.1,
                    unit: "x",
                }),
            },
            SettingInfo {
                group: "Font",
                key: "symbol_fallback",
                env: SYMBOL_FALLBACK_ENV,
                name: "Symbol fallback",
                value: bool_display(self.symbol_fallback).to_owned(),
                description: SYMBOL_FALLBACK_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "symbol_font",
                env: SYMBOL_FONT_ENV,
                name: "Symbol font file",
                value: self
                    .symbol_font
                    .as_ref()
                    .map(|path| path.display().to_string())
                    .unwrap_or_else(|| "auto".to_owned()),
                description: SYMBOL_FONT_DESC,
                kind: SettingKind::Path,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Font",
                key: "symbol_map",
                env: SYMBOL_MAP_ENV,
                name: "Symbol map",
                value: if self.symbol_map.is_empty() {
                    "none".to_owned()
                } else {
                    super::super::format_symbol_map(&self.symbol_map)
                },
                description: "Per-range font override: route Unicode codepoint ranges to named font families (e.g. U+E000-U+F8FF=Symbols Nerd Font; U+2500-U+257F=Fira Code). Semicolon-separated; first match wins. Leaves the body font untouched.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Theme",
                key: "themed_ui_roles",
                env: THEMED_UI_ROLES_ENV,
                name: "Themed UI roles",
                value: bool_display(self.themed_ui_roles).to_owned(),
                description: "Uses theme cursor, selection, and search semantic colors in native UI overlays. Off restores the legacy foreground cursor, inverse selection, and black-on-yellow active search match.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_style",
                env: CURSOR_STYLE_ENV,
                name: "Cursor style",
                value: cursor_style_display(self.cursor_style).to_owned(),
                description: "Default cursor shape shown at startup and after a terminal reset. Running applications may send their own cursor shape requests to override this.",
                kind: SettingKind::Enum,
                range: None,
                options: &["block", "underline", "bar"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_blink",
                env: CURSOR_BLINK_ENV,
                name: "Cursor blink",
                value: self.cursor_blink.as_str().to_owned(),
                description: "Default cursor blink policy at startup. on blinks at a fixed rate; off keeps the cursor steady. auto uses the conventional blinking default (Linux exposes no OS caret-blink preference). An app's DECSCUSR can override any of these at runtime.",
                kind: SettingKind::Enum,
                range: None,
                options: &["auto", "on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_easing",
                env: CURSOR_EASING_ENV,
                name: "Cursor blink fade",
                value: bool_display(self.cursor_easing).to_owned(),
                description: "When on, the cursor eases its opacity in and out across each blink instead of switching hard on and off. On by default; only acts while the cursor is blinking and the window is focused. Purely visual.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_glow",
                env: CURSOR_GLOW_ENV,
                name: "Cursor glow",
                value: bool_display(self.cursor_glow).to_owned(),
                description: "When on, the cursor gets one soft shape-aware analytic aura behind its glyph, matching Block, Bar, or Underline geometry in the resolved cursor color. On by default; the aura is faint enough to keep nearby text readable. Purely visual — never moves the logical cursor.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_glow_intensity",
                env: CURSOR_GLOW_INTENSITY_ENV,
                name: "Cursor glow strength",
                value: format_float(self.cursor_glow_intensity),
                description: "Strength of the cursor glow aura on a 0.0 to 1.0 scale, separate from the whole-scene bloom. 0.0 shows no aura even while Cursor glow is on; the default is a restrained peak; 1.0 is stronger but still bounded so nearby text stays readable and translucent backgrounds are not washed out. Only acts while Cursor glow is on. Purely visual.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_CURSOR_GLOW_INTENSITY,
                    max: MAX_CURSOR_GLOW_INTENSITY,
                    step: 0.05,
                    unit: "",
                }),
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_trail",
                env: CURSOR_TRAIL_ENV,
                name: "Cursor trail",
                value: bool_display(self.cursor_trail).to_owned(),
                description: "When on, a short fading after-image trails the cursor as it glides between cells, in the theme cursor color and drawn behind the cursor block. On by default and visible while Cursor slide is on, which is also the default; it fully decays as the glide settles. Purely visual — never moves the logical cursor.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_trail_strength",
                env: CURSOR_TRAIL_STRENGTH_ENV,
                name: "Cursor trail strength",
                value: self.cursor_trail_strength.as_str().to_owned(),
                description: "Links the nearby cursor echo and large-jump follower under one response profile. balanced preserves the restrained echo and elastic follower; subtle responds faster with less stretch; expressive separates the leading and trailing edges further and settles longer. The logical cursor target and input remain immediate.",
                kind: SettingKind::Enum,
                range: None,
                options: &["subtle", "balanced", "expressive"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_motion",
                env: CURSOR_MOTION_ENV,
                name: "Cursor slide",
                value: bool_display(self.cursor_motion).to_owned(),
                description: "When on, the cursor glides between nearby positions. On by default; with cursor trail enabled, jumps beyond six cells use a bounded elastic follower, while resizes, reflow, scrollback, the first frame, focus loss, and reduced motion snap instantly. Purely visual — the logical cursor is always at the destination cell.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "keybinds",
                env: KEYBINDS_ENV,
                name: "Key bindings",
                value: key_bindings_display(&self.key_bindings),
                description: "Terminal-local shortcut overrides for search, settings, theme picker, command palette, command-output, copy, paste, scrollback, and workspace/pane actions. PTY key encoding is unchanged unless an override captures that chord.",
                kind: SettingKind::List,
                range: None,
                // D-KBR-2: every BindableAction display name, in the exact
                // order of `BindableAction::ALL` (the same order the in-app
                // key-remap editor lists). Display only — the parser already
                // accepts every action. Pinned to `ALL` by
                // `keybinds_info_options_lists_all_actions` so a new variant
                // fails that test until its token is added here.
                options: &[
                    "search",
                    "settings",
                    "theme-picker",
                    "copy",
                    "paste",
                    "scroll-up",
                    "scroll-down",
                    "jump-prompt-prev",
                    "jump-prompt-next",
                    "select-command-output",
                    "select-command-with-prompt",
                    "copy-command-output",
                    "copy-command-with-prompt",
                    "search-command-output",
                    "jump-failed-command-prev",
                    "jump-failed-command-next",
                    "export-command-output",
                    "notify-command-finished",
                    "copy-mode",
                    "hints",
                    "clear-input",
                    "command-palette",
                    "connection-manager",
                    "session-replay",
                    "theme-builder",
                    "session-attach",
                    "new-tab",
                    "new-window",
                    "next-tab",
                    "prev-tab",
                    "close-tab",
                    "duplicate-tab",
                    "new-workspace",
                    "duplicate-workspace",
                    "close-workspace",
                    "rename-workspace",
                    "next-workspace",
                    "prev-workspace",
                    "workspace-picker",
                    "split-columns",
                    "split-rows",
                    "focus-pane-left",
                    "focus-pane-right",
                    "focus-pane-up",
                    "focus-pane-down",
                    "focus-pane-next",
                    "close-pane",
                    "zoom-pane",
                    "equalize-panes",
                ],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Panes",
                key: "pane_prefix",
                env: PANE_PREFIX_ENV,
                name: "Pane prefix",
                value: pane_prefix_display(self.pane_prefix),
                description: "Multiplexer prefix chord (default ctrl+b) that opens the transient pane-command mode: prefix then % or \" to split, arrows or o to focus, x to close, z to zoom, space or = to equalize. Press the prefix twice to send a literal prefix to the focused pane (for a nested multiplexer). Set to off to disable.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "scroll_wheel_lines",
                env: SCROLL_WHEEL_LINES_ENV,
                name: "Scroll wheel speed",
                value: format_float(self.scroll_wheel_lines),
                description: "Rows of scrollback the mouse wheel advances per notch. Affects local scrolling only; when a full-screen program captures the mouse, the wheel still reports to it unchanged.",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_SCROLL_WHEEL_LINES,
                    max: MAX_SCROLL_WHEEL_LINES,
                    step: 1.0,
                    unit: "lines",
                }),
            },
            SettingInfo {
                group: "Input",
                key: "scrollback_lines",
                env: SCROLLBACK_LINES_ENV,
                name: "Scrollback limit",
                value: format_float(self.scrollback_lines),
                description: "Maximum lines of history kept in scrollback before the oldest are dropped. Caps memory use so a program printing endless output cannot exhaust RAM. Set to 0 for unlimited history (use with care).",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_SCROLLBACK_LINES,
                    max: MAX_SCROLLBACK_LINES,
                    step: 1000.0,
                    unit: "lines",
                }),
            },
            SettingInfo {
                group: "Input",
                key: "selection_drag_extend",
                env: SELECTION_DRAG_EXTEND_ENV,
                name: "Drag to extend selection",
                value: bool_display(self.selection_drag_extend).to_owned(),
                description: "When on, double-click then drag extends the selection by whole words, triple-click then drag by whole lines, and Shift+click extends the current selection. On by default; turn off to restore click-to-finish selection.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "scroll_drag_speed",
                env: SCROLL_DRAG_SPEED_ENV,
                name: "Drag autoscroll speed",
                value: self.scroll_drag_speed.as_str().to_owned(),
                description: SCROLL_DRAG_SPEED_DESC,
                kind: SettingKind::Enum,
                range: None,
                options: &["ramp", "legacy"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "pixel_scroll",
                env: PIXEL_SCROLL_ENV,
                name: "Pixel-precise scrolling",
                value: bool_display(self.pixel_scroll).to_owned(),
                description: "When on, high-resolution wheels and touchpads scroll the viewport by a continuous sub-row amount that tracks physical finger travel, instead of quantizing to whole notches. On by default; affects only pixel-precise input, so classic detented wheels are unchanged.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "scroll_pixel_speed",
                env: SCROLL_PIXEL_SPEED_ENV,
                name: "Pixel scroll speed",
                value: format_float(self.scroll_pixel_speed),
                description: "Sensitivity multiplier for pixel-precise (touchpad / hi-res wheel) scrolling. 1.0 tracks finger travel exactly; higher scrolls faster than the finger, lower slower. Applies only to pixel-precise input, never to detented wheels (see Scroll wheel speed for those).",
                kind: SettingKind::Number,
                range: None,
                options: &[],
                reloadable: true,
                numeric: Some(NumericSpec {
                    min: MIN_SCROLL_PIXEL_SPEED,
                    max: MAX_SCROLL_PIXEL_SPEED,
                    step: 0.25,
                    unit: "x",
                }),
            },
            SettingInfo {
                group: "Input",
                key: "scroll_glide",
                env: SCROLL_GLIDE_ENV,
                name: "Animated scroll glide",
                value: bool_display(self.scroll_glide).to_owned(),
                description: "When on, a wheel notch still moves the viewport instantly, but the rendered view eases toward the new position over a few frames for a smoother glide. On by default; affects only detented wheels (high-resolution wheels and touchpads use Pixel-precise scrolling instead).",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "scrollbar_drag",
                env: SCROLLBAR_DRAG_ENV,
                name: "Draggable scrollbar",
                value: bool_display(self.scrollbar_drag).to_owned(),
                description: "When on, grab the right-edge scroll indicator and drag to scrub through scrollback. The thumb only appears while scrolled back into history. On by default; turn off to keep the indicator display-only.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "wheel_zoom",
                env: WHEEL_ZOOM_ENV,
                name: "Ctrl+wheel font zoom",
                value: bool_display(self.wheel_zoom).to_owned(),
                description: "When on, hold Ctrl and scroll the wheel to grow or shrink the font size. On by default; it only acts while a full-screen program is not capturing the mouse, so the plain wheel still scrolls. Turn off to use Ctrl+wheel for scrollback instead.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "sh_click",
                env: SH_CLICK_ENV,
                name: "Click to position cursor",
                value: bool_display(self.sh_click).to_owned(),
                description: "When on, a plain left click in the typed command line moves the input cursor to the clicked spot, including across soft-wrapped lines. Requires a shell that advertises click support via its command-boundary marks; a drag still selects and Shift+click still extends a selection. On by default; without an integrated shell it does nothing.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "command_status_gutter",
                env: COMMAND_STATUS_GUTTER_ENV,
                name: "Command status gutter",
                value: bool_display(self.command_status_gutter).to_owned(),
                description: "When on, draws a thin colored bar in the left margin beside each finished command: green for success, red for a non-zero exit. Requires a shell that emits command-boundary marks. On by default; without an integrated shell the plain left margin stays empty.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "buttons",
                env: BUTTONS_ENV,
                name: "Clickable buttons",
                value: bool_display(self.buttons).to_owned(),
                description: "When on, programs can mark runs of their output as clickable buttons, and clicking one sends its numeric code back to the program. New sessions also receive ODYTTY_BUTTONS=1 in their environment so scripts can detect support. On by default; when off, button sequences are ignored, nothing renders differently, and clicks never send anything.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "buttons_iterm_compat",
                env: BUTTONS_ITERM_COMPAT_ENV,
                name: "Buttons: iTerm2 compatibility",
                value: bool_display(self.buttons_iterm_compat).to_owned(),
                description: "When on, buttons may also be defined with the iTerm2 escape-sequence spelling, so tools written for iTerm2's custom buttons work unchanged. Does nothing while clickable buttons are off.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "buttons_sticky",
                env: BUTTONS_STICKY_ENV,
                name: "Buttons: sticky lifetime",
                value: bool_display(self.buttons_sticky).to_owned(),
                description: "When on, a program may ask for a button that stays clickable after its command finishes, working from scrollback until dismissed or scrolled off. When off, such requests fall back to the normal lifetime that ends at the next prompt. Does nothing while clickable buttons are off.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "shell_integration",
                env: SHELL_INTEGRATION_ENV,
                name: "Shell integration",
                value: bool_display(self.shell_integration).to_owned(),
                description: "Master switch: when on, new local shell tabs receive OdyTTY's integration at spawn, enabling prompt-aware editing and navigation (OSC 133 marks, OSC 7 cwd, click-to-position) without modifying shell rc files. What it delivers depends on the shell: bash, zsh, and fish get prompt marks, cwd, and button emitters (zsh and fish also report the edited line); PowerShell is supported on Windows only, where key bindings use the Console API rather than a VT protocol; nushell is configured natively in its own config, not injected. Applies only to shells OdyTTY launches (nested shells, sudo, and exec-swaps are not covered). On by default (opt-out); existing shells are unchanged until restarted.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Shell Integration",
                key: "shell_key_enhancement",
                env: SHELL_KEY_ENHANCEMENT_ENV,
                name: "Prompt key enhancement (bash/zsh)",
                value: bool_display(self.shell_key_enhancement).to_owned(),
                description: "When on, integrated bash and zsh shells enable the Kitty keyboard protocol (disambiguate mode) while the prompt is active, then turn it off before each command runs. Modified keys become distinct sequences and ship working default binds out of the box: Ctrl+Backspace deletes the previous word, Shift+Enter inserts a newline, Ctrl+Enter submits. Each default is skipped when you have already bound the sequence in inputrc or with bindkey, so a personal bind wins; programs the shell launches are unaffected. Requires shell integration to be on. fish drives the protocol itself and PowerShell uses the Console API, so neither needs this. Off by default: disambiguate mode re-encodes every Ctrl+key as a CSI-u sequence, so while the prompt is active Ctrl+C sends no 0x03 and raises no SIGINT, and Ctrl+D and Ctrl+Z lose EOF and SIGTSTP the same way. zsh can bind its way back to send-break; readline has no function that raises SIGINT, so bash cannot. Turn this on only if you are prepared to bind the Ctrl+keys your prompt needs.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "confirm_close",
                env: CONFIRM_CLOSE_ENV,
                name: "Confirm close when running",
                value: bool_display(self.confirm_close).to_owned(),
                description: "When on, asks for confirmation before closing the window if a program is still running in the terminal. On by default — the prompt only appears when a foreground job is active, so closing an idle shell still exits immediately. Off closes on request unconditionally.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "warn_on_risky_paste",
                env: WARN_ON_RISKY_PASTE_ENV,
                name: "Warn before risky paste",
                value: bool_display(self.warn_on_risky_paste).to_owned(),
                description: "When on (default), multiline or control-bearing text opens a bounded escaped preview before any bytes reach a child that has bracketed-paste mode disabled. Safe single-line text and child-enabled bracketed paste keep their existing byte path. Off is an advanced opt-out that sends text through the historical encoder without a warning.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "bell",
                env: BELL_ENV,
                name: "Bell",
                value: self.bell.as_str().to_owned(),
                description: "How the terminal reacts when a program rings the bell (BEL). Off ignores it. Visual flashes the screen briefly. Urgent (default) requests window attention when unfocused without flashing. All does both. There is no audible bell.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "visual", "urgent", "all"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "notifications",
                env: NOTIFICATIONS_ENV,
                name: "Command and terminal notifications",
                value: self.notifications.as_str().to_owned(),
                description: "Presentation for bounded command-completion and OSC notification hints. In-app (default) keeps transient owned badges only. Attention requests window-manager attention. Desktop attempts a native notification with generic application-owned wording. Off disables presentation. BEL remains controlled separately.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "in-app", "attention", "desktop"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "interactive_urls",
                env: INTERACTIVE_URLS_ENV,
                name: "Clickable URLs",
                value: bool_display(self.interactive_urls).to_owned(),
                description: "On by default. When on, a bare http(s):// (or other allowlisted-scheme) URL that a program printed gets a hand cursor on hover and a Ctrl+hover underline; Ctrl+click opens it in your browser. URLs are never auto-opened, never run through a shell, and only allowlisted schemes (http, https, file, mailto) open. Detection is local-only and scans only the hovered row of the focused pane. Off makes the URL scan never run (byte-identical hover). Independent of Interactive file paths; explicit OSC 8 hyperlinks are handled separately.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
            SettingInfo {
                group: "Input",
                key: "interactive_paths",
                env: INTERACTIVE_PATHS_ENV,
                name: "Interactive file paths",
                value: bool_display(self.interactive_paths).to_owned(),
                description: "Off by default, so the pointer path never scans terminal text and the plain hover path is byte-identical. When on, hovering a path-looking span that resolves to a real file or directory shows the pointer (hand) cursor. Detection is local-only (nothing is logged, persisted, or sent) and the single filesystem check happens only on a hovered candidate. Hover works on the focused pane only.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
                numeric: None,
            },
        ];
        rows.extend(super::catalog_tail::tail_setting_rows(self));
        rows.sort_by_key(|row| setting_group_rank(row.group));
        for row in &mut rows {
            if row.range.is_none()
                && let Some(spec) = row.numeric
            {
                row.range = Some(numeric_range_label(spec));
            }
        }
        rows
    }
}
