#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# OdyTTY glyph fixture corpus — generator / runner.
#
# Emits a single public-safe, fully-synthetic Unicode corpus to stdout that
# exercises every glyph family OdyTTY must render. It is intentionally free of
# any real shell history, local paths, hostnames, or personal data — it contains
# only Unicode codepoints and short synthetic labels.
#
# Usage
# -----
#   Eyeball in odytty (prints corpus + labels):
#       python3 scripts/glyph-fixture.py
#       # or inside an odytty session:
#       cat tests/fixtures/glyphs.txt
#
#   Regenerate the committed static corpus:
#       python3 scripts/glyph-fixture.py > tests/fixtures/glyphs.txt
#
#   Then keep them in sync:
#       cargo fmt --check && cargo test --test glyph_corpus
#
# What each section checks (see the section headers in the output for details):
#   * Box drawing / block elements / Braille    — core geometric coverage
#   * Sextants, octants, triangles, eighths      — Symbols for Legacy Computing
#                                                  (newly added geometric ranges)
#   * Deferred ranges                            — documented holes; expect
#                                                  font fallback / tofu until a
#                                                  later phase closes them
#   * Powerline + Nerd Font PUA samples          — the icon/symbol fallback path
#                                                  (the screenshot regression)
#   * CJK wide                                   — 2-cell width handling
#   * Combining marks                            — base + combining diacritics
#   * Emoji (ZWJ / flag / keycap)                — grapheme cluster width
#
# Requires only python3 (no third-party packages).

import sys

WIDE = "=" * 72
THIN = "-" * 72


def line(text=""):
    out.append(text)


def section(title, blurb, ranges_blurb=""):
    line("# " + WIDE)
    line("# " + title)
    for b in blurb:
        line("# " + b)
    if ranges_blurb:
        line("# " + ranges_blurb)
    line("# " + THIN)


def end_section():
    line()


def chunked(start, end, per_line=16):
    """Emit codepoints start..=end (inclusive) as space-separated rows."""
    cps = list(range(start, end + 1))
    for i in range(0, len(cps), per_line):
        row = cps[i : i + per_line]
        cells = " ".join(chr(c) for c in row)
        line("# U+{:04X}..U+{:04X}".format(row[0], row[-1]))
        line(cells)
    line()


out = []

# ---------------------------------------------------------------- banner
line("# " + WIDE)
line("# OdyTTY glyph fixture corpus")
line("# Fully synthetic — no real shell history, paths, hostnames, or personal data.")
line("# Generated by scripts/glyph-fixture.py; committed copy: tests/fixtures/glyphs.txt")
line("# Eyeball: python3 scripts/glyph-fixture.py  |  cat tests/fixtures/glyphs.txt")
line("# " + WIDE)
line()

# ----------------------------------------------------- box drawing
section(
    "Box drawing  (U+2500..U+257F)",
    [
        "Light/heavy/double lines, corners, tees, crosses, dashes, arcs, and",
        "diagonals. OdyTTY renders these geometrically (font-independent). Check",
        "that segments join seamlessly across cell boundaries and that heavy and",
        "double variants stay distinct.",
    ],
    ranges_blurb="# Range: U+2500..U+257F",
)
chunked(0x2500, 0x257F, per_line=16)

# ----------------------------------------------------- block elements
section(
    "Block elements  (U+2580..U+259F)",
    [
        "Half/full blocks, quadrants, shades, and one-eighth blocks. Renders",
        "geometrically. Verify full-block cells are opaque and shades are distinct.",
    ],
    ranges_blurb="# Range: U+2580..U+259F",
)
chunked(0x2580, 0x259F, per_line=16)

# ----------------------------------------------------- braille
section(
    "Braille patterns  (U+2800..U+28FF)",
    [
        "256 dot patterns on a 2x4 grid, rendered geometrically. Verify the blank",
        "pattern is empty, the full pattern fills the cell, and single-dot corners",
        "land in the right place.",
    ],
    ranges_blurb="# Range: U+2800..U+28FF (full set)",
)
chunked(0x2800, 0x28FF, per_line=32)
end_section()

# ----------------------------------------------------- sextants
section(
    "Symbols for Legacy Computing — sextants  (U+1FB00..U+1FB3B)",
    [
        "2-column x 3-row cell-division fills (60 glyphs). Rendered geometrically.",
        "Region 1 = top-left; 1..3 fill the left column, 4..6 the right column.",
    ],
    ranges_blurb="# Range: U+1FB00..U+1FB3B (full set, geometric)",
)
chunked(0x1FB00, 0x1FB3B, per_line=15)

# ----------------------------------------------------- octants
section(
    "Symbols for Legacy Computing Supplement — octants  (U+1CD00..U+1CDE5)",
    [
        "2-column x 4-row cell-division fills (230 glyphs). Rendered geometrically.",
        "Regions 1..4 fill the left column, 5..8 the right column.",
    ],
    ranges_blurb="# Range: U+1CD00..U+1CDE5 (full set, geometric)",
)
chunked(0x1CD00, 0x1CDE5, per_line=15)

# ----------------------------------------------------- triangles
section(
    "Symbols for Legacy Computing — triangular blocks  (U+1FB68..U+1FB6F)",
    [
        "Edge-apex quarter triangles and their three-quarter complements.",
        "Rendered geometrically with 1px anti-aliased edges.",
    ],
    ranges_blurb="# Range: U+1FB68..U+1FB6F (full set, geometric)",
)
chunked(0x1FB68, 0x1FB6F, per_line=8)

# ----------------------------------------------------- eighths / shades
section(
    "Symbols for Legacy Computing — eighth strips, ladders, half-shades",
    [
        "Vertical/horizontal one-eighth strips, L-combo one-eighth edge blocks,",
        "upper/right eighth ladders, half-shades, and seven-segment digits 0-9.",
        "All rendered geometrically.",
    ],
    ranges_blurb="# Covered: U+1FB70..U+1FB81, U+1FB82..U+1FB8B, U+1FB8C..U+1FB8F, U+1FBF0..U+1FBF9 (geometric)",
)
chunked(0x1FB70, 0x1FB7B, per_line=12)
line("# L-combo one-eighth blocks + horizontal block-1358  (U+1FB7C..U+1FB81)")
line(" ".join(chr(c) for c in range(0x1FB7C, 0x1FB81 + 1)))
line()
chunked(0x1FB82, 0x1FB8B, per_line=10)
chunked(0x1FB8C, 0x1FB8F, per_line=8)
line("# seven-segment digits 0-9  (U+1FBF0..U+1FBF9)")
line(" ".join(chr(c) for c in range(0x1FBF0, 0x1FBF9 + 1)))
line()

# ----------------------------------------------------- deferred holes
section(
    "DEFERRED — known holes (expect font fallback / tofu)",
    [
        "These Symbols for Legacy Computing ranges are NOT yet rendered",
        "geometrically. With symbol_fallback on they may resolve via the bundled",
        "symbols font; otherwise expect tofu. The corpus intentionally surfaces",
        "them so progress is visible.",
    ],
    ranges_blurb="# Holes: U+1FB3C..U+1FB67, U+1FBBD..U+1FBBF (need an AA polygon filler)",
)
line("# diagonal-edged blocks  (U+1FB3C..U+1FB67)")
chunked(0x1FB3C, 0x1FB67, per_line=15)
line("# negative diagonals  (U+1FBBD..U+1FBBF)")
line(" ".join(chr(c) for c in range(0x1FBBD, 0x1FBBF + 1)))
end_section()

# ----------------------------------------------------- powerline
section(
    "Powerline symbols  (U+E0A0..U+E0C0 area)",
    [
        "Geometrically-drawn chevrons/slants and the branch/line-column glyphs.",
        "The chevrons are drawn geometrically; the others exercise the symbol",
        "fallback path.",
    ],
    ranges_blurb="# Range: U+E0A0, U+E0A2, U+E0A3, U+E0B0..U+E0B3, U+E0B4..U+E0B7, U+E0C0..U+E0C6, U+E0C8, U+E0CC..U+E0CE",
)
line(
    " ".join(
        chr(c)
        for c in [
            0xE0A0, 0xE0A2, 0xE0A3,
            0xE0B0, 0xE0B1, 0xE0B2, 0xE0B3,
            0xE0B4, 0xE0B5, 0xE0B6, 0xE0B7,
            0xE0C0, 0xE0C4, 0xE0C5, 0xE0C6, 0xE0C8, 0xE0CC, 0xE0CD, 0xE0CE,
        ]
    )
)
end_section()

# ----------------------------------------------------- nerd font PUA samples
section(
    "Nerd Font PUA samples (symbol fallback path)",
    [
        "A representative handful of Nerd Font private-use glyphs (folder, git,",
        "home, terminal, distro logos). Exact codepoints vary by Nerd Font",
        "version; this sample exercises the bundled symbols fallback that fixes",
        "the original tofu-beside-prompt regression. With symbol_fallback ON these",
        "resolve from the bundled Symbols Nerd Font Mono face.",
    ],
    ranges_blurb="# FontAwesome/Seti/Codicons/fonts-logos PUA (version-dependent)",
)
nf_samples = [
    (0xE725, "git branch  (devicons nf-dev-git_branch)"),
    (0xF07C, "folder open (FontAwesome nf-fa-folder_open)"),
    (0xF015, "home        (FontAwesome nf-fa-home)"),
    (0xF120, "terminal    (FontAwesome nf-fa-terminal)"),
    (0xF1D3, "git logo    (FontAwesome nf-fa-git)"),
    (0xF0302, "arch logo   (fonts-logos nf-linux-archlinux)"),
    (0xF031F, "debian logo (fonts-logos nf-linux-debian)"),
    (0xF02D2, "tux logo    (fonts-logos nf-linux-linuxmint / tux area)"),
    (0xEAFC, "git branch  (codicons nf-cod-git_branch)"),
    (0xE264, "branch      (seti nf-seti-git_branch)"),
]
line("glyph  meaning")
for cp, desc in nf_samples:
    line("{:s}     {:s}".format(chr(cp), desc))
end_section()

# ----------------------------------------------------- CJK wide
section(
    "CJK wide text (2-cell width)",
    [
        "Han / Hiragana / Katakana / Hangul and fullwidth Latin should each occupy",
        "two cells. Verify no overlap with the following cell and correct cursor",
        "advance.",
    ],
)
line("# Han / Japanese / Korean")
line("漢字  日本語  한국어  漢語  변환  數學")
line()
line("# fullwidth Latin + halfwidth katakana")
line("ＡＢＣ１２３  ｱｲｳｴｵ")
end_section()

# ----------------------------------------------------- combining marks
section(
    "Combining marks (base + combining diacriticals)",
    [
        "Base letter followed by one or more combining marks (U+0300..U+036F).",
        "Verify the mark sits on the base glyph and the cluster occupies one cell.",
    ],
)
line("e\u0301 = e + combining acute   (expected: \u00e9)")
line("n\u0303 = n + combining tilde   (expected: \u00f1)")
line("a\u0308 = a + combining diaeresis (expected: \u00e4)")
line("o\u0302 = o + combining circumflex (expected: \u00f4)")
line("u\u0301\u0308 = u + acute + diaeresis (stacked)")
line("o\u0328 = o + combining ogonek")
line("A\u030A = A + combining ring above (expected: \u00c5)")
end_section()

# ----------------------------------------------------- emoji
section(
    "Emoji (ZWJ sequence / flag / keycap)",
    [
        "Grapheme clusters that must render as a single wide glyph. The ZWJ",
        "sequence uses U+200D; the flag uses regional indicator pairs; the keycap",
        "uses U+FE0F + U+20E3. Verify width and no stray component glyphs.",
    ],
)
line("# ZWJ family sequence")
line("family:  \U0001F469\u200D\U0001F469\u200D\U0001F467   (woman ZWJ woman ZWJ girl)")
line("technologist:  \U0001F468\u200D\U0001F4BB   (man ZWJ laptop)")
line()
line("# flag (regional indicator pair)")
line("JP:  \U0001F1EF\U0001F1F5   GB:  \U0001F1EC\U0001F1E7   EU:  \U0001F1EA\U0001F1FA")
line()
line("# keycap (digit + variation selector + combining enclosing keycap)")
line("1\uFE0F\u20E3  2\uFE0F\u20E3  #\uFE0F\u20E3")
line()
line("# single emoji baseline")
line("\U0001F600  \U0001F680  \u2705  \u274C  \U0001F4BB")
end_section()

# ---------------------------------------------------------------- trailer
line("# " + WIDE)
line("# End of corpus.")
line("# " + WIDE)

sys.stdout.write("\n".join(out) + "\n")
