#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# Regenerate the Unicode-derived bidi data that OdyTTY commits:
#
#   * src/core/bidi/mirrored.rs: the Bidi_Mirrored=Yes ranges from
#     DerivedBinaryProperties.txt.
#   * tests/fixtures/unicode-bidi/BidiCharacterTest-subset.txt and
#     BidiTest-subset.txt: deterministic strided subsets of the two UAX #9
#     conformance files, with every @Levels and @Reorder header kept so each
#     retained BidiTest data line keeps its expected result.
#
# Usage: unicode-bidi-data.py <directory holding the three UCD files>
#
# The input files come from https://www.unicode.org/Public/<version>/ucd/
# (BidiCharacterTest.txt, BidiTest.txt) and .../ucd/extracted/
# (DerivedBinaryProperties.txt). Their SHA-256 values are written into each
# generated header so a later run can prove which release produced them.
# Standard library only.

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

CHARACTER_TEST_STRIDE = 32
CLASS_TEST_STRIDE = 64

REPO = Path(__file__).resolve().parent.parent
FIXTURES = REPO / "tests" / "fixtures" / "unicode-bidi"
MIRRORED_RS = REPO / "src" / "core" / "bidi" / "mirrored.rs"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def first_line(path: Path) -> str:
    return path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip()


def header(source: Path, stride: int, kind: str) -> list[str]:
    return [
        f"# Strided subset of {first_line(source)} ({kind}).",
        f"# Source SHA-256: {sha256(source)}",
        f"# Kept: one {kind} line in every {stride}, starting with the first, in file order.",
        "# Copyright Unicode, Inc. Distributed under the Unicode License v3;",
        "# see LICENSE-UNICODE.txt beside this file.",
        "# Regenerate with scripts/unicode-bidi-data.py.",
    ]


def character_subset(source: Path) -> list[str]:
    # The file interleaves left-to-right and right-to-left cases, so a plain
    # stride would keep almost only one direction. Count each paragraph
    # direction separately; the few auto-direction cases are all kept.
    out = header(source, CHARACTER_TEST_STRIDE, "data")
    out[2] = (
        f"# Kept: one data line in every {CHARACTER_TEST_STRIDE} per paragraph "
        "direction (0 and 1), starting with the first, plus every direction 2 line."
    )
    seen: dict[str, int] = {}
    for line in source.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        direction = line.split(";")[1].strip()
        index = seen.get(direction, 0)
        seen[direction] = index + 1
        if direction == "2" or index % CHARACTER_TEST_STRIDE == 0:
            out.append(line)
    return out


def class_subset(source: Path) -> list[str]:
    out = header(source, CLASS_TEST_STRIDE, "data")
    index = 0
    pending: list[str] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        if line.startswith("@"):
            pending = [p for p in pending if not p.startswith(line.split(":")[0])]
            pending.append(line)
            continue
        if index % CLASS_TEST_STRIDE == 0:
            out.extend(pending)
            pending = []
            out.append(line)
        index += 1
    return out


def mirrored_table(source: Path) -> str:
    ranges = []
    for line in source.read_text(encoding="utf-8").splitlines():
        body = line.split("#")[0].strip()
        if not body:
            continue
        span, prop = (part.strip() for part in body.split(";"))
        if prop != "Bidi_Mirrored":
            continue
        start, end = span.split("..") if ".." in span else (span, span)
        ranges.append((int(start, 16), int(end, 16)))
    ranges.sort()
    merged: list[tuple[int, int]] = []
    for start, end in ranges:
        if merged and start <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
        else:
            merged.append((start, end))
    rows, row = [], "   "
    for start, end in merged:
        item = f" ('\\u{{{start:04X}}}', '\\u{{{end:04X}}}'),"
        if len(row) + len(item) > 100:
            rows.append(row)
            row = "   "
        row += item
    rows.append(row)
    count = sum(end - start + 1 for start, end in merged)
    return "\n".join(
        [
            "// SPDX-License-Identifier: GPL-3.0-only",
            "//! Bidi_Mirrored=Yes code point ranges, generated by",
            "//! `scripts/unicode-bidi-data.py` from",
            f"//! {first_line(source)} (SHA-256",
            f"//! {sha256(source)}).",
            "//! The data is Unicode Character Database content, Copyright Unicode, Inc.,",
            "//! under the Unicode License v3 (tests/fixtures/unicode-bidi/LICENSE-UNICODE.txt).",
            "//! Do not edit by hand.",
            "",
            f"/// {len(merged)} merged ranges covering {count} code points, sorted and disjoint.",
            "#[rustfmt::skip]",
            "pub(super) const BIDI_MIRRORED: &[(char, char)] = &[",
            *rows,
            "];",
            "",
        ]
    )


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__ or "usage: unicode-bidi-data.py <ucd dir>", file=sys.stderr)
        return 2
    ucd = Path(sys.argv[1])
    FIXTURES.mkdir(parents=True, exist_ok=True)
    (FIXTURES / "BidiCharacterTest-subset.txt").write_text(
        "\n".join(character_subset(ucd / "BidiCharacterTest.txt")) + "\n", encoding="utf-8"
    )
    (FIXTURES / "BidiTest-subset.txt").write_text(
        "\n".join(class_subset(ucd / "BidiTest.txt")) + "\n", encoding="utf-8"
    )
    MIRRORED_RS.parent.mkdir(parents=True, exist_ok=True)
    MIRRORED_RS.write_text(mirrored_table(ucd / "DerivedBinaryProperties.txt"), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
