#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Extract Unicode 17 names for geometrically drawn legacy-computing blocks.

Usage: unicode-legacy-names.py UnicodeData.txt > tests/fixtures/unicode-legacy-computing/names.txt
Source: https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
Standard library only. Keeps the code point and name fields of the sextants,
octants, triangular blocks, and upper and right ladders.
"""
import hashlib
import sys
from pathlib import Path

PIN = '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'
RANGES = [
    (0x1FB00, 0x1FB3B),  # sextants
    (0x1CD00, 0x1CDE5),  # octants
    (0x1FB68, 0x1FB6F),  # triangular blocks
    (0x1FB82, 0x1FB8B),  # upper and right ladders
]


def main():
    path = Path(sys.argv[1])
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != PIN:
        sys.exit(f'UnicodeData.txt SHA-256 {digest} does not match the pin')
    names = {}
    for line in data.decode('utf-8').splitlines():
        fields = line.split(';')
        if len(fields) > 1:
            names[int(fields[0], 16)] = fields[1]
    out = [
        '# Unicode 17 character names; Unicode-3.0, see LICENSE-UNICODE.txt.',
        '# Generated by scripts/unicode-legacy-names.py.',
        f'# UnicodeData.txt SHA-256: {PIN}',
    ]
    for low, high in RANGES:
        for cp in range(low, high + 1):
            if cp not in names:
                sys.exit(f'U+{cp:04X} is unassigned in the pinned data')
            out.append(f'{cp:04X};{names[cp]}')
    sys.stdout.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
