#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate bounded G1/G2 tables and conformance fixtures from Unicode 17.0.0 UCD.

Usage: unicode-indic-data.py <directory holding UnicodeData.txt, Scripts.txt,
IndicSyllabicCategory.txt, DerivedCoreProperties.txt, GraphemeBreakProperty.txt,
GraphemeBreakTest.txt>. Inputs: https://www.unicode.org/Public/17.0.0/ucd/
(the two GraphemeBreak files are in auxiliary/). Standard library only.
"""
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parent.parent
G1 = ('Devanagari', 'Bengali', 'Gurmukhi', 'Gujarati', 'Oriya')
G2 = ('Tamil', 'Telugu', 'Kannada', 'Malayalam')
NAMES = G1 + G2

def properties(path):
    out = {}
    for line in path.read_text().splitlines():
        fields = line.split('#')[0].strip().split(';')
        if len(fields) < 2:
            continue
        ends = fields[0].strip().split('..')
        start, end = int(ends[0], 16), int(ends[-1], 16)
        value = ';'.join(x.strip() for x in fields[1:])
        out.update((cp, value) for cp in range(start, end + 1))
    return out

def ranges(values):
    out = []
    for cp, value in sorted(values.items()):
        if out and out[-1][1] + 1 == cp and out[-1][2] == value:
            out[-1] = (out[-1][0], cp, value)
        else:
            out.append((cp, cp, value))
    return out

def main():
    source = Path(sys.argv[1])
    for name in ('Scripts.txt', 'IndicSyllabicCategory.txt', 'DerivedCoreProperties.txt', 'GraphemeBreakProperty.txt', 'GraphemeBreakTest.txt'):
        if '17.0.0' not in (source / name).read_text().splitlines()[0]:
            raise ValueError(f'{name}: Unicode 17.0.0 is required')
    scripts = properties(source / 'Scripts.txt')
    isc = properties(source / 'IndicSyllabicCategory.txt')
    gcb = properties(source / 'GraphemeBreakProperty.txt')
    incb = properties(source / 'DerivedCoreProperties.txt')
    cats = {int(f[0], 16): f[2] for line in (source / 'UnicodeData.txt').read_text().splitlines() if (f := line.split(';'))}
    ids = {name: i + 1 for i, name in enumerate(NAMES)}
    scope = {cp: ids[script] for cp, script in scripts.items() if script in ids}
    groups = {
        'BASES': {cp: sid for cp, sid in scope.items() if cats.get(cp, '').startswith('L')},
        'CONSONANTS': {cp: sid for cp, sid in scope.items() if isc.get(cp) == 'Consonant'},
        'SPACING': {cp: sid for cp, sid in scope.items() if cats.get(cp) == 'Mc'},
        'LINKERS': {cp: sid for cp, sid in scope.items() if isc.get(cp) in ('Virama', 'Invisible_Stacker')},
        'EXTEND': {cp: 0 for cp, value in gcb.items() if value == 'Extend'},
    }
    header = ['// SPDX-License-Identifier: GPL-3.0-only', '// Generated by scripts/unicode-indic-data.py; Unicode 17.0.0.', '// Do not edit by hand.', '// Copyright Unicode, Inc.; tests/fixtures/unicode-indic/LICENSE-UNICODE.txt.']
    for name in ('UnicodeData.txt', 'Scripts.txt', 'IndicSyllabicCategory.txt', 'GraphemeBreakProperty.txt'):
        header.append(f'// {name} SHA-256: {hashlib.sha256((source / name).read_bytes()).hexdigest()}')
    text = header[:]
    for name, values in groups.items():
        text.append(f'pub(super) const {name}: &[(u32, u32, u8)] = &[')
        text.extend(f'    (0x{a:x}, 0x{b:x}, {sid}),' for a, b, sid in ranges(values))
        text.append('];')
    (ROOT / 'src/core/indic/data.rs').write_text('\n'.join(text) + '\n')
    fixture = ROOT / 'tests/fixtures/unicode-indic'
    data = ['# Unicode 17.0.0 G1 property subset; Unicode-3.0, see LICENSE-UNICODE.txt.', '# Generated by scripts/unicode-indic-data.py.']
    for name in ('Scripts.txt', 'IndicSyllabicCategory.txt', 'DerivedCoreProperties.txt', 'UnicodeData.txt'):
        data.append(f'# {name} SHA-256: {hashlib.sha256((source / name).read_bytes()).hexdigest()}')
    for cp, sid in sorted(scope.items()):
        if scripts[cp] not in G1:
            continue
        data.append(f'{cp:04X};{sid};{cats.get(cp,"Cn")};{isc.get(cp,"Other")};{incb.get(cp,"None")}')
    (fixture / 'G1-properties.txt').write_text('\n'.join(data) + '\n')
    original = source / 'GraphemeBreakTest.txt'
    lines = ['# Unicode 17.0.0 GraphemeBreakTest G1 subset; Unicode-3.0.', '# See LICENSE-UNICODE.txt. Generated by scripts/unicode-indic-data.py.', f'# Source SHA-256: {hashlib.sha256(original.read_bytes()).hexdigest()}', '# Kept all rows starting in G1 BASES with other scalars in G1, ZWJ, ZWNJ, or U+0308.']
    for line in original.read_text().splitlines():
        body = line.split('#')[0].strip()
        if not body:
            continue
        cps = [int(x, 16) for x in body.split() if x not in ('÷', '×')]
        if scripts.get(cps[0]) in G1 and cps[0] in groups['BASES'] and all(scripts.get(cp) in G1 or cp in (0x200c, 0x200d, 0x308) for cp in cps):
            lines.append(line)
    (fixture / 'GraphemeBreakTest-G1.txt').write_text('\n'.join(lines) + '\n')
    # Fixture ids are local to the bounded script group, independent of the
    # production table ids. Preserve the G2 property corpus and source hashes.
    data = ['# Unicode 17.0.0 G2 properties; Unicode-3.0, see LICENSE-UNICODE.txt.',
            '# Scripts: 1 Tamil, 2 Telugu, 3 Kannada, 4 Malayalam.',
            '# Columns: scalar;script-id;General_Category;Indic_Syllabic_Category;GCB;DerivedCoreProperties final assignment.']
    for name in ('Scripts.txt', 'UnicodeData.txt', 'IndicSyllabicCategory.txt', 'DerivedCoreProperties.txt', 'GraphemeBreakProperty.txt'):
        data.append(f'# {name} SHA-256: {hashlib.sha256((source / name).read_bytes()).hexdigest()}')
    for cp in sorted(scope):
        if scripts[cp] in G2:
            sid = G2.index(scripts[cp]) + 1
            data.append(f'{cp:04X};{sid};{cats.get(cp,"Cn")};{isc.get(cp,"Other")};{gcb.get(cp,"Other")};{incb.get(cp,"None")}')
    (fixture / 'G2-properties.txt').write_text('\n'.join(data) + '\n')

if __name__ == '__main__':
    main()
