#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate bounded Unicode 17 emoji width data. Standard library only.

Usage: unicode-emoji-data.py DIRECTORY containing the four pinned files.
Sources: https://www.unicode.org/Public/17.0.0/ucd/emoji/ and
https://www.unicode.org/Public/17.0.0/emoji/ for sequence files.
"""
from pathlib import Path
import hashlib
import sys

ROOT = Path(__file__).resolve().parent.parent
PINS = {'emoji-data.txt': '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b', 'emoji-variation-sequences.txt': 'bb3d09ef03f206012c7532dd52dc0a21c9efddba0135ea4cf0d9201b8b9bba7e', 'emoji-sequences.txt': '12cc8267dc33cbd11ed32bcf6fc5dc2ad9c7a77bae1bdfba2f41b1b9b3ead8dd', 'emoji-zwj-sequences.txt': '5b25441daed2322b068c5e70cda522946a4f0274df864445a1965a92e5fc5cad'}

def rows(path):
    for line in path.read_text().splitlines():
        fields = line.split('#')[0].strip().split(';')
        if len(fields) > 1:
            yield fields[0].strip(), fields[1].strip()

def ranges(values):
    out = []
    for cp in sorted(values):
        if out and out[-1][1] + 1 == cp:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out

def main():
    source = Path(sys.argv[1])
    for name, sha in PINS.items():
        if hashlib.sha256((source / name).read_bytes()).hexdigest() != sha:
            raise ValueError(f'{name}: pinned Unicode 17 input required')
    modifier_bases = set()
    for value, prop in rows(source / 'emoji-data.txt'):
        if prop == 'Emoji_Modifier_Base':
            ends = value.split('..')
            modifier_bases.update(range(int(ends[0], 16), int(ends[-1], 16) + 1))
    variation_bases = {int(value.split()[0], 16) for value, prop in rows(source / 'emoji-variation-sequences.txt') if prop == 'emoji style'}
    sequences = sorted(tuple(int(cp, 16) for cp in value.split()) for value, prop in rows(source / 'emoji-zwj-sequences.txt') if prop == 'RGI_Emoji_ZWJ_Sequence')
    assert all(1 < len(seq) <= 17 for seq in sequences)
    header = ['// SPDX-License-Identifier: GPL-3.0-only', '// Generated by scripts/unicode-emoji-data.py; Unicode 17.0.', '// Do not edit by hand.', '// Copyright Unicode, Inc.; tests/fixtures/unicode-emoji/LICENSE-UNICODE.txt.']
    header += [f'// {name} SHA-256: {sha}' for name, sha in PINS.items()]
    output = header[:]
    for name, values in [('VS16_BASES', variation_bases), ('MODIFIER_BASES', modifier_bases)]:
        output.append(f'pub(super) const {name}: &[(u32, u32)] = &[')
        output.extend(f'    (0x{start:x}, 0x{end:x}),' for start, end in ranges(values))
        output.append('];')
    # Split generated rows so formatting cannot exceed the production limit.
    midpoint = (len(sequences) + 1) // 2
    for name, subset in [('zwj_first', sequences[:midpoint]), ('zwj_second', sequences[midpoint:])]:
        table = header + ['pub(super) const SEQUENCES: &[&[u32]] = &[']
        table.extend('    &[' + ', '.join(f'0x{cp:x}' for cp in seq) + '],' for seq in subset)
        table.append('];')
        (ROOT / f'src/core/emoji_width/{name}.rs').write_text('\n'.join(table) + '\n')
    output.append('pub(super) const ZWJ_TABLES: [&[&[u32]]; 2] = [super::zwj_first::SEQUENCES, super::zwj_second::SEQUENCES];')
    (ROOT / 'src/core/emoji_width/data.rs').write_text('\n'.join(output) + '\n')
    fixture = ['# Unicode 17 emoji width fixtures; Unicode-3.0, see LICENSE-UNICODE.txt.', '# Generated by scripts/unicode-emoji-data.py.']
    fixture += [f'# {name} SHA-256: {sha}' for name, sha in PINS.items()]
    for value, prop in rows(source / 'emoji-variation-sequences.txt'):
        if prop == 'emoji style':
            fixture.append(value + ';VS16')
    for value, prop in rows(source / 'emoji-sequences.txt'):
        if prop in ('RGI_Emoji_Modifier_Sequence', 'Emoji_Keycap_Sequence', 'RGI_Emoji_Flag_Sequence'):
            fixture.append(value + ';' + prop)
    fixture.extend(' '.join(f'{cp:04X}' for cp in seq) + ';RGI_Emoji_ZWJ_Sequence' for seq in sequences)
    (ROOT / 'tests/fixtures/unicode-emoji/G7-sequences.txt').write_text('\n'.join(fixture) + '\n')

if __name__ == '__main__':
    main()
