use super::*;

/// Broad setting type hint for the read-only UX2-a panel and later editors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingKind {
    Bool,
    Enum,
    Number,
    String,
    Path,
    List,
}

/// Static/dynamic metadata for one settings row in stable display order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SettingInfo {
    pub group: &'static str,
    pub key: &'static str,
    pub env: &'static str,
    pub name: &'static str,
    pub value: String,
    pub description: &'static str,
    pub kind: SettingKind,
    pub range: Option<&'static str>,
    pub options: &'static [&'static str],
    pub reloadable: bool,
}

impl Settings {
    /// Stable read-only inventory for the in-app settings panel.
    ///
    /// This intentionally mirrors every field on [`Settings`]. UX2-b can attach
    /// editors and persistence to the same rows; UX2-a only displays them.
    pub fn setting_info(&self) -> Vec<SettingInfo> {
        vec![
            SettingInfo {
                group: "Theme",
                key: "theme",
                env: THEME_ENV,
                name: "Theme",
                value: self.theme.name.to_owned(),
                description: "Full appearance profile: default colors, ANSI palette, semantic role colors, and optional user theme files.",
                kind: SettingKind::Enum,
                range: None,
                options: &[
                    "plain",
                    "odyssey",
                    "odyssey-noir",
                    "user theme name",
                    "theme file path",
                ],
                reloadable: true,
            },
            SettingInfo {
                group: "Theme",
                key: "visual",
                env: VISUAL_ENV,
                name: "Visual effect",
                value: self.visual.as_str().to_owned(),
                description: "Optional presentation-only visual treatment. Off is the plain renderer and remains the safest fast path.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "ambient"],
                reloadable: true,
            },
            SettingInfo {
                group: "Font",
                key: "font",
                env: FONT_ENV,
                name: "Font file",
                value: self
                    .font_path
                    .as_ref()
                    .map(|path| path.display().to_string())
                    .unwrap_or_else(|| "default monospace probe list".to_owned()),
                description: "Explicit font file path. Takes precedence over font_family and falls back safely when unreadable.",
                kind: SettingKind::Path,
                range: None,
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Font",
                key: "font_family",
                env: FONT_FAMILY_ENV,
                name: "Font family",
                value: self
                    .font_family
                    .clone()
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "System font family lookup for the regular monospace face. Ignored when an explicit font file is set.",
                kind: SettingKind::String,
                range: None,
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Font",
                key: "font_size",
                env: FONT_SIZE_ENV,
                name: "Font size",
                value: format_float(self.font_size_px),
                description: "Native font size in pixels. Rebuilds the glyph atlas, cell metrics, terminal grid, and PTY window size.",
                kind: SettingKind::Number,
                range: Some("6.0..=72.0 px"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "text_gamma",
                env: TEXT_GAMMA_ENV,
                name: "Text gamma",
                value: format_float(self.text_gamma),
                description: "Glyph coverage gamma applied in the shader for text weight and contrast.",
                kind: SettingKind::Number,
                range: Some("0.5..=3.0"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "stem_darken",
                env: STEM_DARKEN_ENV,
                name: "Stem darkening",
                value: format_float(self.stem_darken),
                description: STEM_DARKEN_DESC,
                kind: SettingKind::Number,
                range: Some("0.0..=1.0"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "min_contrast",
                env: MIN_CONTRAST_ENV,
                name: "Minimum contrast",
                value: format_float(self.min_contrast),
                description: MIN_CONTRAST_DESC,
                kind: SettingKind::Number,
                range: Some("1.0..=21.0"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "focus_dim",
                env: FOCUS_DIM_ENV,
                name: "Focus dimming",
                value: format_float(self.focus_dim),
                description: FOCUS_DIM_DESC,
                kind: SettingKind::Number,
                range: Some("0.0..=1.0"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "render_quality",
                env: RENDER_QUALITY_ENV,
                name: "Render quality",
                value: self.render_quality.as_str().to_owned(),
                description: RENDER_QUALITY_DESC,
                kind: SettingKind::Enum,
                range: None,
                options: &["plain", "balanced", "high"],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom",
                env: BLOOM_ENV,
                name: "Bloom",
                value: bool_display(self.bloom).to_owned(),
                description: BLOOM_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_threshold",
                env: BLOOM_THRESHOLD_ENV,
                name: "Bloom threshold",
                value: format_float(self.bloom_threshold),
                description: BLOOM_THRESHOLD_DESC,
                kind: SettingKind::Number,
                range: Some("0.70..=1.25"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_intensity",
                env: BLOOM_INTENSITY_ENV,
                name: "Bloom intensity",
                value: format_float(self.bloom_intensity),
                description: BLOOM_INTENSITY_DESC,
                kind: SettingKind::Number,
                range: Some("0.0..=1.0"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "bloom_radius",
                env: BLOOM_RADIUS_ENV,
                name: "Bloom radius",
                value: format_float(self.bloom_radius),
                description: BLOOM_RADIUS_DESC,
                kind: SettingKind::Number,
                range: Some("0.5..=8.0 px"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "crt",
                env: CRT_ENV,
                name: "CRT profile",
                value: bool_display(self.crt).to_owned(),
                description: CRT_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_scanline_intensity",
                env: CRT_SCANLINE_INTENSITY_ENV,
                name: "CRT scanlines",
                value: format_float(self.crt_scanline_intensity),
                description: CRT_SCANLINE_INTENSITY_DESC,
                kind: SettingKind::Number,
                range: Some("0.0..=0.18"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_scanline_period",
                env: CRT_SCANLINE_PERIOD_ENV,
                name: "CRT scanline period",
                value: format_float(self.crt_scanline_period),
                description: CRT_SCANLINE_PERIOD_DESC,
                kind: SettingKind::Number,
                range: Some("2.0..=12.0 px"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Post-process",
                key: "crt_vignette_strength",
                env: CRT_VIGNETTE_STRENGTH_ENV,
                name: "CRT vignette",
                value: format_float(self.crt_vignette_strength),
                description: CRT_VIGNETTE_STRENGTH_DESC,
                kind: SettingKind::Number,
                range: Some("0.0..=0.16"),
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "subpixel",
                env: SUBPIXEL_ENV,
                name: "Subpixel AA",
                value: subpixel_display(self.subpixel).to_owned(),
                description: "Optional RGB/BGR subpixel text coverage. Unsupported adapters fall back to grayscale.",
                kind: SettingKind::Enum,
                range: None,
                options: &["off", "rgb", "bgr"],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "synthetic_styles",
                env: SYNTHETIC_STYLES_ENV,
                name: "Synthetic styles",
                value: bool_display(self.synthetic_styles).to_owned(),
                description: "Synthesizes missing bold and italic faces from the regular font when real style faces are unavailable.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "geometric_boxdraw",
                env: GEOMETRIC_BOXDRAW_ENV,
                name: "Geometric box-drawing",
                value: bool_display(self.geometric_boxdraw).to_owned(),
                description: GEOMETRIC_BOXDRAW_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "symbol_fallback",
                env: SYMBOL_FALLBACK_ENV,
                name: "Symbol fallback",
                value: bool_display(self.symbol_fallback).to_owned(),
                description: SYMBOL_FALLBACK_DESC,
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Rendering",
                key: "symbol_font",
                env: SYMBOL_FONT_ENV,
                name: "Symbol font",
                value: self
                    .symbol_font
                    .as_ref()
                    .map(|path| path.display().to_string())
                    .unwrap_or_else(|| "auto".to_owned()),
                description: SYMBOL_FONT_DESC,
                kind: SettingKind::Path,
                range: None,
                options: &[],
                reloadable: true,
            },
            SettingInfo {
                group: "Theme",
                key: "themed_ui_roles",
                env: THEMED_UI_ROLES_ENV,
                name: "Themed UI roles",
                value: bool_display(self.themed_ui_roles).to_owned(),
                description: "Uses theme cursor, selection, and search semantic colors in native UI overlays. Off restores the legacy foreground cursor, inverse selection, and black-on-yellow active search match.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_style",
                env: CURSOR_STYLE_ENV,
                name: "Cursor style",
                value: cursor_style_display(self.cursor_style).to_owned(),
                description: "Host default cursor shape used at startup and after terminal reset. Applications can still override it.",
                kind: SettingKind::Enum,
                range: None,
                options: &["block", "underline", "bar"],
                reloadable: true,
            },
            SettingInfo {
                group: "Cursor",
                key: "cursor_blink",
                env: CURSOR_BLINK_ENV,
                name: "Cursor blink",
                value: self.cursor_blink.as_str().to_owned(),
                description: "Host default cursor blink policy. Auto currently resolves to blinking and is reserved for future system preference support.",
                kind: SettingKind::Enum,
                range: None,
                options: &["auto", "on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Input",
                key: "keybinds",
                env: KEYBINDS_ENV,
                name: "Key bindings",
                value: key_bindings_display(&self.key_bindings),
                description: "Terminal-local shortcut overrides for search, settings, theme picker, copy, paste, and scrollback actions. PTY key encoding is unchanged.",
                kind: SettingKind::List,
                range: None,
                options: &[
                    "search",
                    "settings",
                    "theme-picker",
                    "copy",
                    "paste",
                    "scroll-up",
                    "scroll-down",
                ],
                reloadable: true,
            },
            SettingInfo {
                group: "Clipboard",
                key: "osc52_read",
                env: OSC52_READ_ENV,
                name: "OSC 52 read",
                value: bool_display(self.osc52_read).to_owned(),
                description: "Allows terminal applications to query local clipboard contents through OSC 52 replies. Off by default for safety.",
                kind: SettingKind::Bool,
                range: None,
                options: &["on", "off"],
                reloadable: true,
            },
            SettingInfo {
                group: "Development",
                key: "native_autoclose_ms",
                env: NATIVE_AUTOCLOSE_ENV,
                name: "Native autoclose",
                value: self
                    .native_autoclose
                    .map(|duration| format!("{} ms", duration.as_millis()))
                    .unwrap_or_else(|| "unset".to_owned()),
                description: "Smoke-test helper that closes the native window after a startup delay. It is startup-only, not live-reloadable.",
                kind: SettingKind::Number,
                range: Some("positive milliseconds"),
                options: &[],
                reloadable: false,
            },
        ]
    }
}
