// SPDX-License-Identifier: GPL-3.0-only
pub mod app;
pub mod atlas;
pub mod boxdraw;
pub mod color;
pub mod core;
pub mod emoji;
pub mod graphics;
pub mod grid;
pub mod input;
pub mod native;
pub mod parser;
pub mod pty;
pub mod render;
pub mod selection;
pub mod settings;
pub mod text;
pub mod theme;
